### ISSUE TITLE
How to pass my custom cmake build parameters？

### ISSUE THREAD

**Issue by msclock** [scikit-build/scikit-build-core#147]
Thank you for your efforts with the python and cmake build tools. 
But I am new to the tool. For example, there are still some doubts about how to pass parameters to the cmake build phase. 

Using scikit-build,I just use the command `pip install . --config-settings=--build-option='--build-type=RelWithDebInfo -j8'`.
But switch to scikit-build-core,I feel a little confused about how to pass the parameters in the build phase.

**Comment by henryiii** [comment]
The normal way is to use `--config-settings=cmake.define.<name>=<value>`, or you can use `cmake.args` for configuration args. You can also set defaults for these in `pyproject.toml`. But build-type is special (as it was before in scikit-build), so that's `--config-settings=cmake.build-type=RelWithDebInfo`. Currently, you have to pass the parallel setting via environment variable, `CMAKE_BUILD_PARALLEL_LEVEL=8 pip install --config-settings=cmake.build-type=RelWithDebInfo` would be identical to the line you gave above. I've been thinking about having a cmake.parallel, just like we have a `cmake.verbose` shortcuts for `CMAKE_VERBOSE_MAKEFILE`. Note that scikit-build-core tries to use Ninja if it knowns it can get it (unless you turn off `ninja.make-fallback` or manually set CMAKE_GENERATOR), so it's much less likely that you'll need the parallel setting (Ninja uses all your cores by default).

**Comment by msclock** [comment]
> The normal way is to use `--config-settings=cmake.define.<name>=<value>`, or you can use `cmake.args` for arbitrary configuration args (semicolon separated, pip doesn't support arrays). You can also set defaults for these in `pyproject.toml`. But build-type is special (as it was before in scikit-build - it's handled differently for some generators), so that's `--config-settings=cmake.build-type=RelWithDebInfo`. Currently, you have to pass the parallel setting via environment variable,
> 
> ```shell
> CMAKE_BUILD_PARALLEL_LEVEL=8 pip install --config-settings=cmake.build-type=RelWithDebInfo
> ```
> 
> would be identical to the line you gave above.
> 
> I've been thinking about having a `cmake.parallel` (`-j` at build time) shortcut, just like we have a `cmake.verbose` shortcut for `CMAKE_VERBOSE_MAKEFILE` (`-v` at build time). Build-phase arguments are limited, so there's no way to pass arbitrary ones like there is at the configuration phase. Note that scikit-build-core tries to use Ninja if it knowns it can get it (unless you turn off `ninja.make-fallback` or manually set `CMAKE_GENERATOR`), so it's much less likely that you'll need the parallel setting (Ninja uses all your cores by default, and it can also build targets in parallel, unlike make). (Also that maybe should be `build.parallel` and `build.verbose`, that's part of why I have't settled on it yet)
> 
> (Example of changing the default in `pyproject.toml` - you can still override on the command line):
> 
> ```toml
> [tool.cmake]
> cmake.build-type = "RelWithDebInfo"
> ```
Well, passing as env is truelly a workaround sovling my life.Thank you very much for answering questions in time.
I will continue to follow up and use the best tools.

**Comment by msclock** [comment]
> The normal way is to use `--config-settings=cmake.define.<name>=<value>`, or you can use `cmake.args` for arbitrary configuration args (semicolon separated, pip doesn't support arrays). You can also set defaults for these in `pyproject.toml`. But build-type is special (as it was before in scikit-build - it's handled differently for some generators), so that's `--config-settings=cmake.build-type=RelWithDebInfo`. Currently, you have to pass the parallel setting via environment variable,
> 
> ```shell
> CMAKE_BUILD_PARALLEL_LEVEL=8 pip install --config-settings=cmake.build-type=RelWithDebInfo
> ```
> 
> would be identical to the line you gave above.
> 
> I've been thinking about having a `cmake.parallel` (`-j` at build time) shortcut, just like we have a `cmake.verbose` shortcut for `CMAKE_VERBOSE_MAKEFILE` (`-v` at build time). Build-phase arguments are limited, so there's no way to pass arbitrary ones like there is at the configuration phase. Note that scikit-build-core tries to use Ninja if it knowns it can get it (unless you turn off `ninja.make-fallback` or manually set `CMAKE_GENERATOR`), so it's much less likely that you'll need the parallel setting (Ninja uses all your cores by default, and it can also build targets in parallel, unlike make). (Also that maybe should be `build.parallel` and `build.verbose`, that's part of why I have't settled on it yet)
> 
> (Example of changing the default in `pyproject.toml` - you can still override on the command line):
> 
> ```toml
> [tool.cmake]
> cmake.build-type = "RelWithDebInfo"
> ```
Well, passing as env is truelly a workaround sovling my life.Thank you very much for answering questions in time.
I will continue to follow up and use this best tool.
