### ISSUE TITLE
Do not resolve program links

### ISSUE THREAD

**Issue by agoose77** [scikit-build/scikit-build-core#170]
`pyodide-build` uses an _interesting_ system of shimming the various binaries used during a typical C++ build. It involves the creation of symlinks which point to the same executable (`_pywasmcross`). This executable uses `sys.argv` to determine which binary was being called, which consequently breaks under scikit-build-core.

Is there a need for scikit-build-core to resolve symlinks, or can we just use the result of `shutil.which` directly?

It's not immediately obvious to me why this is suddenly a problem after upgrading to `pyodide==0.22.0`; the code that generates these links has not changed recently, neither has the program resolution in `scikit-build-core`.

**Comment by henryiii** [comment]
I think this is fixed in main, could you check?
