### ISSUE TITLE
Fails to detect Python on `cibuildwheel`

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#173]
Might be an issue of how the CI is implemented, but I've tried to  run `cibuildwheel` locally for Python version `3.6-3.11`, all of which fail to detect Python:
```
  scikit_build_core - WARNING - Can't find a Python library, got libdir=/opt/_internal/cpython-3.10.9/lib, ldlibrary=libpython3.10.a, multiarch=x86_64-linux-gnu, masd=None

 CMake Error at /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Python (missing: Python_LIBRARIES Interpreter Development
        NumPy Development.Module Development.Embed) (found version "3.10.9")
      Call Stack (most recent call first):
        /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.25/Modules/FindPython.cmake:561 (find_package_handle_standard_args)
        python/CMakeLists.txt:1 (find_package)
```

**Comment by henryiii** [comment]
This is not an issue with cibuildwheel (we test on cibuildwheel heavily, see pybind11/scikit_build_example), but with `Development.Embed` being included by default in `Development`. You have to use `COMPONENTS Interpreter NumPy Development.Embed` instead. Manylinux does not ship the static libraries for Python, since they are not needed for building extension modules, and it's a bug to link to them, and they would bloat the Docker container.

**Comment by LecrisUT** [comment]
Actually it is related to `cibuildwheel` and/or cmake `FindPython` detection. Check [this comment](https://github.com/pypa/cibuildwheel/issues/639#issuecomment-818020937). Essentially if you set `find_package(Python REQUIRED ...)`, the system fails. But for unclear reasons to me, if you remove the `REQUIRED`, it works fine. But as I commented there, that is not an ideal "fix"

**Comment by henryiii** [comment]
You need to use `find_package(Python COMPONENTS Interpreter Development.Module REQUIRED)`. It is absolutely not supported to look for the `Development.Embed` component (and thereby the Development meta component) on manylinux; that component is intentionally deleted to save space and stop a common mistake. You certainly can put REQUIRED (and should). See https://github.com/scikit-build/scikit-build-sample-projects/blob/b3772297dcabf21033e41ead6518a2eff8eb34b2/projects/core-c-hello/CMakeLists.txt#L5 for example.

**Comment by LecrisUT** [comment]
Indeed you're right. Sorry for the misunderstanding
