### ISSUE TITLE
Local tests fail with missing cmake package

### ISSUE THREAD

**Issue by bennyrowland** [scikit-build/scikit-build-core#189]
I just cloned the repo, set up a new venv and installed nox into it, then ran `nox`. I got a large number of test failures (24, to be exact), all reporting that cmake was not available. After some digging around, I found that in the ci, cmake is installed in the test env before running the tests, which does not happen in the local nox tests. A simple `session.install("cmake")` in the tests section of `noxfile.py` makes all the tests pass again. Is there an alternative solution you would prefer instead? I am happy to submit a PR, or you can make the change yourself, if it is easier, as it is such a small change.

**Comment by henryiii** [comment]
It works if you have cmake externally installed (I run the nox texts on my machine all the time, but I expect I'd see your 24 failures if I unlinked cmake first). The GHA runners would also have CMake available by default (though we force a specific version via an action).

I do rather like being able to test that not using the cmake package works too. Maybe the nox tests should check to see if cmake is present & sufficient, and only install it if it's not. Or maybe it's best to just assume the nox tests shouldn't care about system packages, and always install it for nox. I agree the current situation is not great.
