### ISSUE TITLE
FedoraProject package

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#196]
In preparation for distributing to FedoraProject, I have prepared a git repository of the `.spec` file:
https://github.com/LecrisUT/scikit-build-core-rpm

The linked copr project is at https://copr.fedorainfracloud.org/coprs/lecris/scikit-build-core/
If there is anything missing, let me know

**Comment by LecrisUT** [comment]
Didn't take long, already could use some help on this build against `0.1.6`: https://copr.fedorainfracloud.org/coprs/lecris/scikit-build-core/build/5521479/

On Fedora 37 and Fedora 38 there are different errors. I'll try to build it with main head as well.

**Comment by henryiii** [comment]
The problem I saw was from using VCS version. I've been sort of planning to remove VCS versioning - while I usually like it, it usually involves setuptools_scm (via hatch-vcs in this case, but still), which changes the way setuptools works for all builds, not just the one you are attempting. This is particularly bad for a build backend, as some distributors have trouble separating dependencies required for build and install (Spack is the biggest offender here).

For the other archs, you need cmake & ninja as dependencies if you are on a platform that doesn't support binary wheels. In general, though, as a distributor, you probably always want your version of cmake and ninja as required dependencies, and you might want to disable the isolated tests (`-m "not isolated"`) if they fail.

**Comment by henryiii** [comment]
> Edit: Against main, the issue is that the package version requirements are too high

Which ones?

**Comment by LecrisUT** [comment]
>  It depends on if you are targeting building with isolation or without isolation

For the FedoraProject, it should be non-isolated. Are there any special flags to force it to be non-isolated?

> Either ninja or make should be in the requirements, with Ninja pretty strongly preferred.

Yes, that's possible in rpm specs. I need to refresh my knowledge on how to call it. But we still need them in `BuildRequirements` in order to run `pytest` right?

> I mean the VCS version for scikit-build-core itself.

Got it. But was this one of the causes of the build failures?

> `pyhton-scikit-build-core`

Oh yes. Typos will be the death of me.

**Comment by henryiii** [comment]
> Are there any special flags to force it to be non-isolated?

Those should already be there in build scripts, but yes, there are flags for both pip and build to avoid isolation. Packaging should usually not be isolated, and users usually build isolated (but those users also won't need the repackaged version)

> But we still need them in BuildRequirements in order to run pytest right?

Ideally, yes, you should have these when testing.

> But was this one of the causes of the build failures?

Yes, I think this was one of the build failures, it was trying to get the version from VCS and it was a shallow checkout or something like that.

**Comment by LecrisUT** [comment]
> > Are there any special flags to force it to be non-isolated?
> 
> Those should already be there in build scripts, but yes, there are flags for both pip and build to avoid isolation. Packaging should usually not be isolated, and users usually build isolated (but those users also won't need the repackaged version)

Hopefully those can be passed in the spec macro:
```
%pyproject_wheel
```

I've disabled the isolation tests, and trying to see if it can sometimes get passed the python dependency requirements. But alas it doesn't seem to collaborate

**Comment by henryiii** [comment]
The only failure I see is the lack of pytest 7.2 (I can reduce the dependency to 7.0 without problems, it's just for a nicer traceback) and pytest-subprocess 1.5 (this should probably be updated in Fedora). Maybe I don't know where to look, though.

**Comment by LecrisUT** [comment]
Here is the page for pytest-subprocess:
https://src.fedoraproject.org/rpms/python-pytest-subprocess

We might be able to backport the updates there to Fedora 37, but at least getting it working on rawhide is a starting point.

**Comment by henryiii** [comment]
Looks like there's an issue here: https://bugzilla.redhat.com/show_bug.cgi?id=2165202

It should be a fairly straightforward update, it's just got two features and a fix (all of which I contributed in support of scikit-build-core). https://pytest-subprocess.readthedocs.io/en/latest/history.html#id1

**Comment by LecrisUT** [comment]
Yeah, those issues are automatically generated as reminders for the maintainers. Might be updated soon though since it's only been 2 weeks ago. Although to get them back-ported to older versions it needs to be requested.

On the note of package maintainers, it would be helpful to add this spec file in this repo with appropriate webhook to copr. That way a copr build will be triggered at any tag release. We can then monitor for build status and update fedoraproject repo accordingly more easily. Similarly for scikit-build.

**Comment by henryiii** [comment]
FYI, 0.2.0 is out, with one fewer dependency (distlib) and slightly relaxed pytest requirement.

I'm okay to add something to this repo if it's possible to test it in some way.

**Comment by LecrisUT** [comment]
Oh I understand the errors now. Previously it was erroring at the build stage, and it could never get to the test stage. I'll trigger it again tomorrow or when a repo is pushed. For some reason though F37 is failing the build stage again ([log](https://download.copr.fedorainfracloud.org/results/lecris/scikit-build-core/fedora-37-x86_64/05529500-scikit-build-core/builder-live.log.gz))

As for adding the spec and copr, I've opened a PR #201 so we can discuss more there.

**Comment by henryiii** [comment]
Have you tried setting `SETUPTOOLS_SCM_PRETEND_VERSION`? Looks like it can't get the version from git when looking at the log.

**Comment by LecrisUT** [comment]
Unfortunately I don't see a way to prepend environment variables in the spec file. Curiously though only F37 is affected. I'll try to switch it to the version model if it solves it.
