### ISSUE TITLE
Removing the `scikit-build-core` build dependency on git

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#208]
This affects rpm builds that will use the tar balls on the package manager side. Currently these cannot be built because of the dynamic versioning via git.

Any plans or ETAs on this?

**Comment by henryiii** [comment]
The tarballs (either from git archive tarballs or SDists) don't require git. Only a source checkout does (and you can work around this by setting an environment variable).

I am thinking we'll likely do this since in some build systems it causes `setuptools_scm` to leak, changing setuptools builds. But package managers should be able to handle the version part. `scikit-build` classic does exactly the same thing and uses a vcs version, by the way.

**Comment by LecrisUT** [comment]
> The tarballs (either from git archive tarballs or SDists) don't require git

I was referring to `pip install .` on those. You can build `scikit-build-core` without a `.git` folder? I previously had issues building with tito since it uses `git archive`.

> and you can work around this by setting an environment variable

Didn't find a way to add environment variables to the rpm spec macro.

`scikit_build` cheats that because it is getting the pypi archive which might have the version file included? But I couldn't find any such generated file in the github release tar ball. We also want the rpm spec file to be usable by maintainers locally or via copr, for which the tito solution is most advantageous, but it cannot work out of the box yet because of this.

**Comment by henryiii** [comment]
It should be there:

```console
$ cat ~/Downloads/scikit-build-core-0.2.0/.git_archival.txt
node: 7b363782f56e3a528824b814cc805efd23af69d8
node-date: 2023-02-14T17:28:21-05:00
describe-name: v0.2.0
ref-names: tag: v0.2.0
```

Now that 0.2.0 is out, you probably can use the PyPI release here as well.

**Comment by LecrisUT** [comment]
Oh, I need to do some testing around that. Maybe I can just fake that for the pr

**Comment by LecrisUT** [comment]
Thank you, I have confirmed that this is a `tito` issue. Apparently the following approach does not generate the appropriate `.git_archival.txt`

```console
$ git archive HEAD:./
```

If we remove the `:./` it works fine, but I think that would not be ideal on their design. For the time-being I will mock up the file `.git_archival.txt` within the `spec` file so that it can get similar format until it is fixed upstream. This should not affect the official FedoraProject release since it will use the lookaside from the release archive.

Thanks for pointing me in the right direction on this one.
