### ISSUE TITLE
`test_cmake_config.py` fails on local systems

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#209]
Ok, I am embarrassed that it took me so long to realize the tests are failing on my local system as well (Fedora 37):
`fp.register` only registers `fp.program("cmake")` but not variants like `fp.program("cmake3")` which can be used instead
https://github.com/scikit-build/scikit-build-core/blob/084f457780e336a8fe97457cf95d32259b741c27/tests/test_cmake_config.py#L40

Proposed solution: register additional aliases like  `fp.program("cmake3")`, or make sure `scikit-build-core` takes the symlinked version of cmake. Former solution implemented in #201 (954e00319c955c9466d1b670953f4cfeb011e2c0)

**Comment by henryiii** [comment]
That was just an oversight - we should register `cmake3`.

**Comment by henryiii** [comment]
Mind cherry-picking 954e00319c955c9466d1b670953f4cfeb011e2c0 into a new PR? That would also have the benefit that #201 would start building when you push instead of having me click things. :)

**Comment by LecrisUT** [comment]
Kay, cherry-picked it.
