### ISSUE TITLE
Include FetchContent/CPM packages in sdist

### ISSUE THREAD

**Issue by MuellerSeb** [scikit-build/scikit-build-core#249]
Hey there,

thanks for the effort to create this package.

At the moment I am using legacy scikit-build in my project and I am using [CPM](https://github.com/cpm-cmake/CPM.cmake) to get build dependencies.

Since there was a requirement in our group to be able to build the package without Internet connection, I created a custom sdist command, to download the dependencies before creating the dist: `setup.py`
```python
import os
import shutil
import subprocess
import tempfile

import setuptools
import skbuild

class sdist(setuptools.command.sdist.sdist):
    """Custom sdist command to include deps in source distribution."""

    def run(self):
        here = os.getcwd()
        dep_dir = os.path.join(here, "<dep-folder>")
        # remove potentially existing dir
        shutil.rmtree(dep_dir, ignore_errors=True)
        # download dep by calling cmake (CPM will download correct version)
        cmake = skbuild.constants.CMAKE_DEFAULT_EXECUTABLE
        with tempfile.TemporaryDirectory(dir=here) as tmp_dir:
            subprocess.run(
                (cmake, f"-B{tmp_dir}", f"-DCPM_SOURCE_CACHE={here}"),
                capture_output=True,
                cwd=here,
            )
        # CPM stores deps in folder with git-hash as name
        if not os.path.exists(dep_dir) or len(os.listdir(dep_dir)) != 1:
            shutil.rmtree(dep_dir, ignore_errors=True)
            raise RuntimeError("could not download deps.")
        hash_dir = os.path.join(dep_dir, os.listdir(dep_dir)[0])
        # copy contents to '<dep-folder>' top-folder
        shutil.copytree(
            hash_dir, dep_dir, copy_function=shutil.move, dirs_exist_ok=True
        )
        shutil.rmtree(hash_dir)
        # run sdist
        super().run()
        # remove deps dir again
        shutil.rmtree(dep_dir)

skbuild.setup(
    ...
    cmdclass={"sdist": sdist},
)
```

I know this is kind of hacky, but it does exactly what I want. CPM is instructed in the CMakeLists file to use the local folder for the dependency if it is present.

Do you think, there is an option to create workflows like these with `scikit-build-core`? My approach depends on setuptools, so when there is setuptools support in the future it could be possible to use it with scikit-build-core as well, right?

Or do you have any opinion if this could be done better?

Cheers,
Sebastian

**Comment by henryiii** [comment]
Yes, I think there should be such an option in the future. Designing it will be tricky, so I'll probably work on finishing editable installs and getting a few more low-lying fruit before trying to tackle this properly. I think these are the initial ideas:

* Running cmake in the sdist step - also useful for storing CMakeConfig's (pybind11). Easy enough to add an option, but what gets run and stored?
* Providing a hook or an option to run a hook executing Python. Probably will do several things (like selecting what to do if there's a failure)
* Plugin system for looks like CPM. Providing the cmake files is easy, the harder thing is integrating it with (the above?)

You should be able to do this already with git submodules & force-include... Oh, I haven't added force-include yet, never mind. I expect we'll have hatchling's force-include in the future.

Of course, the setuptools support should be able to do this as well. `skbuild.constants.CMAKE_DEFAULT_EXECUTABLE` is the only thing that might change above. The main thing here is that cmake/ninja is not required for the isolated SDist step, so whatever config we select above should also enable cmake/ninja in the SDist step.

> when there is setuptools support in the future

Well, technically, the support is there now, it's just very experimental, a bit incomplete, and subject to change. ;)

**Comment by MuellerSeb** [comment]
Thanks for your insights!

So, `skbuild.constants.CMAKE_DEFAULT_EXECUTABLE` isn't something I should rely on? Is there already a future-proof way to get the cmake executable?

**Comment by henryiii** [comment]
I don't think it will go away, it will likely be a backward-compat item in scikit-build.

**Comment by LecrisUT** [comment]
Bundling dependencies like that might be some licensing issues. There is also the issue of which library is picked depending on `LD_LIBRARY_PATH` values and equivalent logic of the OS. Why are you not building the upstream packages there as static libraries?

**Comment by henryiii** [comment]
This is possible I believe, in the last version or two, with `sdist.cmake = true`.
