### ISSUE TITLE
[tool.cmake] pyproject.toml

### ISSUE THREAD

**Issue by zerothi** [scikit-build/scikit-build-core#275]
It seems to me that all pyproject.toml flags should be tool specific.

I think that the current tools added to the pyproject.toml will polute the file.

In particular I think:
```
[tool.cmake]
```
should be renamed to
```
[tool.scikit-build.cmake]
```
to ensure a correct name space.
This is mainly to not advocate the `cmake` tool which may/ or may not arrive later.

It also makes it more clear where the keys belong too.

Would this make sense for the configuration aspect?

**Comment by zerothi** [comment]
> a) We own the PyPI `CMake` package, so we have access to `tool.cmake`. Ninja too.

Great! Thanks! That clarifies it a lot.

> b) I am not aware of any `tool.cmake` usage, everything is inside `tool.scikit-build`, and yes there is a `tool.scikit-build.cmake`. They configuration design actually kind of forces it. :)

The documentation has `[tool.cmake]` https://scikit-build-core.readthedocs.io/en/latest/configuration.html#configuring-cmake-arguments-and-defines

**Comment by henryiii** [comment]
Oops! That’s a typo.

**Comment by zerothi** [comment]
Great, thanks. Feel free to close, I'll probably come with more questions/feedback as we go along. :)
