### ISSUE TITLE
pyproject_metadata not found

### ISSUE THREAD

**Issue by zerothi** [scikit-build/scikit-build-core#280]
I got this:
```
      from pyproject_metadata import StandardMetadata
  ModuleNotFoundError: No module named 'pyproject_metadata'
```
I can see in your `pyproject.toml` has this as an optional dependency?

I don't know why this happens, but is there a reason why it isn't a required dependency?

I am trying to put *everything* into the `pyproject.toml` :)

I did:
```
python -m pip install scikit-build-core
```
and tried it, but fails with the above. It of course continues if `pyproject-metadata` also gets installed :)

**Comment by henryiii** [comment]
You can use `scikit-build-core[pyproject]`. There’s no harm in doing that, even in your pyproject.toml. Those two dependencies are only used in the pyp 517 builder, and aren’t required when using this as a plug-in builder or using the setuptools plug-in.

Though I’ve been tempted to just require them since they are very light weight.

**Comment by zerothi** [comment]
So I guess the `pyproject-metadata` package is required when `scikit-build` should read stuff from the `pyproject.toml`, isn't that nearly always the case?  
It was just not clear to me that I really needed this when installing it at first. :)

**Comment by henryiii** [comment]
If you are using the (currently only supported) PEP 517 builder, yes. If you are using the experimental setuptools plugin, no (and at least one project is). It's a pretty lightweight pair of dependencies (was a little heavier when we also required distlib), but it's technically not needed for several (eventual) major uses of the library.

I'm very much on the fence about auto-requiring these. I might bring it up as a discussion point at this month's scikit-build Community Meeting on Friday.

**Comment by zerothi** [comment]
Ok, I have worked around by explicitly adding it in my `pyproject` file. Perhaps this should be clarified in https://scikit-build-core.readthedocs.io/en/latest/getting_started.html#python-package-configuration
?

**Comment by zerothi** [comment]
Feel free to close this, unless you want it opened for documentation tracking.

**Comment by hauntsaninja** [comment]
I think it would be good for this to be required, or at least to re-raise the ModuleNotFoundError with a more helpful message
