### ISSUE TITLE
FindPython: Regression on GitHub Actions macOS 11/12 with Python 3.11.3 and CMake 3.26.3

### ISSUE THREAD

**Issue by dalcinl** [scikit-build/scikit-build-core#283]
I originally reported this issue to CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/24811
After doing some local testing on a macOS machine that allowed me to reproduce the failure, maybe the problem  is related to `scikit-build-core` and/or build environment isolation, and not `CMake`. 
For your convenience, I paste below my original issue report to CMake:

FindPython cannot find the `Interpreter Development.Module` components [[logs]](https://github.com/mpi4py/mpi4py/actions/runs/4708595134/jobs/8351125347#step:6:745).

* GitHub-hosted runners
* macOS 11 and 12
* Python 3.11.3 (from `actions/setup-python@v4` with `python_version: 3`)
* CMake 3.26.3 (AFAICT, Hombrew installation in /usr/local)

This is `mpi4py` CI infrastructure trying to build with the new `scikit-build-core` Python build backend at version 0.3.0. The build uses Python from an isolated build environment. Previous builds from 3 days ago where using Python 3.11.2 and CMake 3.26.1, and were [all good](https://github.com/mpi4py/mpi4py/actions/runs/4680812576/jobs/8292622819).

I don't have tons of experience with  `scikit-build-core` or `CMake`. Let me know what else I can do on my side to further debug the issue.

**Comment by henryiii** [comment]
This might be a side effect of adding the python lib location in 0.3.0. I thought this was fixed starting in CMake 3.24 (and we backport before 3.26.1). Could you test with `scikit-build-core<0.3`? We really only need the lib location on Windows.

**Comment by dalcinl** [comment]
> This might be a side effect of adding the python lib location in 0.3.0.

Can you point me to the commit/PR that added this change?


> Could you test with `scikit-build-core<0.3`?

Looks like you may be right, Henry. With `scikit-build-core < 0.3`, [all builds are OK](https://github.com/mpi4py/mpi4py/actions/runs/4709728226).

**Comment by dalcinl** [comment]
BTW, why aren't you testing the latest CMake version in CI? something like `cmake-version: ["3.15.x", "latest"]` in the build matrix should do (according to docs from `jwlawson/actions-setup-cmake`).

**Comment by henryiii** [comment]
https://github.com/scikit-build/scikit-build-core/pull/263 (initial PR and reasoning in scikit-build)

We do test on a matrix. I think this is a fairly specific issue.

**Comment by dalcinl** [comment]
> We do test on a matrix. I think this is a fairly specific issue.

Yes, I know. I noticed you are not testing the latest CMake on all platforms (only Windows), and somehow assumed that this issue is related to latest CMake 3.26.3, not I understand that may not be the case.  

Anyway, many thanks for your prompt action and the new patch release. I confirm #285 fixed the issue in mpi4py CI runs.
