### ISSUE TITLE
cmake rebuild in editable installation does not specify build config

### ISSUE THREAD

**Issue by metab0t** [scikit-build/scikit-build-core#351]
https://github.com/scikit-build/scikit-build-core/blob/12c8b9632421ffffc1c6519195757c9f0ad72771/src/scikit_build_core/resources/_editable_redirect.py#L74
In multi-configuration build system (like Visual Studio), `cmake --build` should also specify `--config <CONFIG>` otherwise it will use the fallback configuration such as `Debug`. 
See [this link](https://stackoverflow.com/a/24470998/13161260) for reference.

PS: `cmake --install` picks the correct configuration automatically.

**Comment by henryiii** [comment]
Pretty sure it doesn't hurt to specify it, so did both. (Later, mirroring `--strip` and `--component` will be important).
