### ISSUE TITLE
example: `swig` use built-in cmake support

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#376]
https://cmake.org/cmake/help/latest/module/UseSWIG.html

Also the documentation labels it as fortran instead of c source code

**Comment by henryiii** [comment]
> Also the documentation labels it as fortran instead of c source code

Where? not seeing that.

**Comment by LecrisUT** [comment]
Ohh, sorry, I was on the phone and the `Fortran` tab looked like a code-block header:
<details><summary>Screenshot</summary>

![Screenshot_20230614-163727](https://github.com/scikit-build/scikit-build-core/assets/25577083/85828eaf-03f0-4d9e-847e-32cde071b6ca)

</details>
