### ISSUE TITLE
Error: `long_description` has syntax errors in markup

### ISSUE THREAD

**Issue by HDembinski** [scikit-build/scikit-build-core#386]
@henryiii recently ported iminuit to scikit-build-core. Everything works great, but upon uploading my wheels, I now get this error: 
https://github.com/scikit-hep/iminuit/actions/runs/5243343680/jobs/9468499640#step:4:17

Copied here in case you cannot see these logs:
```
 ERROR    `long_description` has syntax errors in markup and would not be        
         rendered on PyPI.                                                      
         line 92: Warning: "raw" directive disabled.
```

Can someone help?

Googling, I found this, which may be related:
https://stackoverflow.com/questions/63413288/twine-warning-long-description-content-type-missing

**Comment by henryiii** [comment]
Wow, that's odd. I'd not expect the METADATA to be different. Let me compare the wheels before and after, and see what changed in METADATA. (It looks like it's complaining about the `.. raw: html` directive, but not sure why it didn't complain about that before / why it cares now).

(You can disable this check when uploading, by the way, but let's see why it's happening first)

**Comment by henryiii** [comment]
By the way, your SDist is 166M. I think you are dumping all of ROOT into your SDist. I'd recommend filtering out all the stuff you don't need with include/exclude or `.gitignore`.

**Comment by henryiii** [comment]
You added this new directive after 2.21.3:

https://github.com/scikit-hep/iminuit/compare/v2.21.3...main#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f

It would have produced the same error with setuptools; `.. raw:` is not supported on PyPI (security issue, I think).

I think you can run `twine check` to get see this error before upload; and if not, you can look at the various checks in https://github.com/hynek/build-and-inspect-python-package, one of those checks readme validity.

**Comment by henryiii** [comment]
(Also, you could try moving the readme to markdown, that would support some inline html)

**Comment by henryiii** [comment]
Yes, twice check detects it:

```
pipx run build
pipx run twine check dist/*
Checking dist/iminuit-2.22.0-cp311-cp311-macosx_13_0_x86_64.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.
         line 92: Warning: "raw" directive disabled.
Checking dist/iminuit-2.22.0.tar.gz: FAILED
ERROR    `long_description` has syntax errors in markup and would not be rendered on PyPI.
         line 92: Warning: "raw" directive disabled.
```

**Comment by HDembinski** [comment]
Thank you for the investigation, I would not have guessed that this was the problem. I will close this as it is not a bug in scikit-build-core.
