### ISSUE TITLE
possible typo in `Getting Started` guide

### ISSUE THREAD

**Issue by samuelpmish** [scikit-build/scikit-build-core#424]
see: https://scikit-build-core.readthedocs.io/en/latest/getting_started.html#cmake-file

<img width="795" alt="Screenshot 2023-07-07 at 2 27 22 PM" src="https://github.com/scikit-build/scikit-build-core/assets/16393433/2c6dc995-f1b6-4aad-abd2-bac758223268">

the `nanobind` tab has `pybind11` stuff in the example CMakeLists.txt

**Comment by henryiii** [comment]
Oops, that doesn't look right. IIRC this is including a file from docs/examples, so it's probably grabbing the wrong one.

**Comment by henryiii** [comment]
Yes, this is a typo:

https://github.com/scikit-build/scikit-build-core/blob/04fa2c3210d2b2c7924a89594b0b69ccb22eb6c6/docs/getting_started.md?plain=1#L320
