### ISSUE TITLE
conda-forge: FindPython while cross-compiling can't find numpy on Azure

### ISSUE THREAD

**Issue by MuellerSeb** [scikit-build/scikit-build-core#480]
When cross-compiling on Azure for Aaarch64 and ppc64le for conda-forge, the numpy include dirs can't be found.
This
```cmake
find_package(Python REQUIRED COMPONENTS Interpreter Development.Module NumPy)
```
gives:
```
Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS Interpreter Development.Module NumPy) (found version "3.10.12")
```

Strange thing is, it works on Travis, but rebuilding for pypy includes a transition form Travis to Azure for cross-compiling and there it doesn't work (don't know why...) (See here for reference: https://github.com/conda-forge/mhm-feedstock/pull/15)

I don't know, if this is the correct place to ask for help. Ideas?

Sebastian

**Comment by MuellerSeb** [comment]
Found a workaround:
1. remove Numpy from find_package:
   ```cmake
   find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
   ```
2. get include dirs by hand:
   ```cmake
   execute_process(
     COMMAND "${Python_EXECUTABLE}" -c "import numpy; print(numpy.get_include())"
     OUTPUT_VARIABLE NUMPY_INCLUDE_DIR
     OUTPUT_STRIP_TRAILING_WHITESPACE
   )
   ```
3. replace
   ```cmake
   target_include_directories(${f2py_module_name} PUBLIC ${F2PY_INCLUDE_DIR})
   target_link_libraries(${f2py_module_name} PUBLIC Python::NumPy)
   ```
   with
   ```cmake
   target_include_directories(${f2py_module_name} PUBLIC ${F2PY_INCLUDE_DIR} ${NUMPY_INCLUDE_DIR})
   ```

Then it works.

I see, that something similar is done in [FindPython/Support.cmake](https://github.com/scikit-build/scikit-build-core/blob/c22a7ed3e1e939b538fc43f5fe4bdb6f639169e6/src/scikit_build_core/resources/find_python/FindPython/Support.cmake#L3720).

Is that related?

**Comment by henryiii** [comment]
We might be able to fix this from our side. If `NUMPY_INCLUDE_DIR` is set, I think it will skip looking for it. Though I'm not sure why it's not finding it, since from a glance it does look like it's doing the same thing as the workaround above.

Modern (3.27+) versions of CMake FindPython do have cross compiling support, so that makes me think this might possibly be an issue with it trying to do better at cross compiling.
