### ISSUE TITLE
conda-forge: can't force using ninja

### ISSUE THREAD

**Issue by MuellerSeb** [scikit-build/scikit-build-core#481]
For some reason, I can't get scikit-build-core to use ninja to built the project in a conda-forge feedstock. It always writes
```
  *** Building project with Unix Makefiles...
```

In pyproject.toml, I have:
```toml
[tool.scikit-build.ninja]
minimum-version = "1.11"
make-fallback = false
```
And I also tried setting env-vars:
```
- CMAKE_GENERATOR=Ninja
- SKBUILD_CMAKE_ARGS="-GNinja"
```
But it still uses make. 
Feedstock for reference: https://github.com/conda-forge/mhm-feedstock

I am puzzled here. Any ideas?

Sebastian

**Comment by henryiii** [comment]
Conda-build hardcodes CMAKE_GENERATOR to Makefiles, even if make is not present. You have to set it inside the process to override it, not in the normal env-var setting.

**Comment by LecrisUT** [comment]
Would that still be the case with cmake presets?

**Comment by MuellerSeb** [comment]
Maybe this helps: Creating a `PreLoad.cmake` which sets `CMAKE_GENERATOR`.

https://stackoverflow.com/a/45247784

**Comment by MuellerSeb** [comment]
Update: It seems like forcing ninja with
```
SKBUILD_CMAKE_ARGS="-GNinja"
```
worked already!! Ran into an unrelated build-error and got this message:
```
  *** Building project with Unix Makefiles...
...
  ninja: build stopped: subcommand failed.
```
And without setting `-GNinja` cmake complains that no build-system is found. So I think ninja is used and cmake just prints a missleading `*** Building project with Unix Makefiles...` before compilation.

**Comment by henryiii** [comment]
Yes, that check probably doesn't inspect the cmake args.\

IMO, the nicest way to do this is to set the environment variable, something like this:

```yaml
build:
  script:
    - CMAKE_GENERATOR="Ninja" {{ PYTHON }} -m pip install . -vv
```

Rather than having `CMAKE_GENERATOR` and `-G` both exist and clash.

(Ideally, I'd like Conda-build to stop doing this!)

**Comment by henryiii** [comment]
0.6 is out which should improve handling of args with `-G`.
