### ISSUE TITLE
metadata: Keywords should be stored as comma-separated values

### ISSUE THREAD

**Issue by dalcinl** [scikit-build/scikit-build-core#494]
https://packaging.python.org/en/latest/specifications/core-metadata/#keywords

Keywords are being joined with  spaces in sdist PKG-INFO and wheel METADATA files. I'm not sure this is `scikit-build-core`'s fault. Maybe the root of the issue is from `pyproject_metadata`? In any case, `scikit-build-core` may be interested in adding a workaround.

**Comment by henryiii** [comment]
https://github.com/FFY00/python-pyproject-metadata/pull/61. A new release of pyproject-metadata is needed.

**Comment by dalcinl** [comment]
Should be fixed via pypa/pyproject-metadata#61.
