### ISSUE TITLE
SKBUILD_CMAKE_BUILD_TYPE ignored

### ISSUE THREAD

**Issue by dalcinl** [scikit-build/scikit-build-core#496]
I'm using `scikit_build_core.setuptools.build_meta` as my build backend, and my `pyproject.toml` does not contain the `[project]` section. 

The [documentation](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#configuring-cmake-arguments-and-defines) says (literally!) that we can tweak via environment `SKBUILD_CMAKE_BUILD-TYPE: "Debug"`, note the hyphen `-` in the name. That's quite and odd character for an env var name, and not in the usual portable set. At first, I thought this was a typo in the documentation, but then I realize that running `env SKBUILD_CMAKE_BUILD_TYPE=Debug python -m build -w` actually ignores my request. 

After a quick digging in the codebase, I got to the `EnvSource` class. In there, I'm not seeing `field.replace("_", "-")` as in other related classes used for the settings source chain. Is that indeed a trivial bug, or am I missing something?

**Comment by henryiii** [comment]
Ouch, sounds like a trivial bug! Though this should be tested at https://github.com/scikit-build/scikit-build-core/blob/e1fcf8994b170e7a7ed35d9d3ad3c36525e9a5b1/tests/test_skbuild_settings.py#L75. I wonder if it's actually an issue with using it. Can you enable debug logging and see what it's trying to do?

**Comment by dalcinl** [comment]
> Can you enable debug logging and see what it's trying to do?

I'm not really sure how to do it. Any tips?

**Comment by dalcinl** [comment]
```
$ env SKBUILD_CMAKE_VERBOSE=true SKBUILD_CMAKE_BUILD_TYPE=Debug python -m build -w
...
RUN: /usr/bin/cmake3 -S. -Bbuild/temp.linux-x86_64-cpython-311/_skbuild -Cbuild/temp.linux-x86_64-cpython-311/_skbuild/CMakeInit.txt -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_MAKE_PROGRAM=/home/dalcinl/.local/bin/ninja
...
```

**Comment by dalcinl** [comment]
I tried setting the env variable with a hyphen within ipython, and still does not work. Looks like you where right, the problem is somewhere else.

```
$ ipython --no-banner
In [1]: import os
In [2]: os.environ['SKBUILD_CMAKE_VERBOSE']='true'
In [3]: os.environ['SKBUILD_CMAKE_BUILD-TYPE']='Debug'
In [4]: os.system("python -m build -w")
...
RUN: /usr/bin/cmake3 -S. -Bbuild/temp.linux-x86_64-cpython-311/_skbuild -Cbuild/temp.linux-x86_64-cpython-311/_skbuild/CMakeInit.txt -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_MAKE_PROGRAM=/home/dalcinl/.local/bin/ninja
...
```

**Comment by LecrisUT** [comment]
Could you check the CMakeCache.txt as well? It should be passed through `-Cbuild/temp.linux-x86_64-cpython-311/_skbuild/CMakeInit.txt`. Although it should still not be picked up because of the overload. It would be useful to have an integration test there as well to check for cli variables and for the actual values in CMakeCache.txt.

**Comment by dalcinl** [comment]
> Could you check the CMakeCache.txt as well?

```
$ grep CMAKE_BUILD_TYPE -r build/temp.linux-x86_64-cpython-311/_skbuild/
build/temp.linux-x86_64-cpython-311/_skbuild/CMakeCache.txt:CMAKE_BUILD_TYPE:STRING=Release
```

**Comment by henryiii** [comment]
Ahh, `scikit_build_core.setuptools.build_meta` has it hardcoded based on the envvar `DEBUG`, following setuptools. In general, the settings are less likely to have an effect in setuptools mode.

What we probably should do is default to cmake.build_type unless DEBUG is set, in which case we force a debug build.

**Comment by dalcinl** [comment]
What `DEBUG` setuptools env var are you talking about? I know about `DISTUTILS_DEBUG`, but that one is related to verbose output, and not compiler flags or cmake-style build type.

**Comment by henryiii** [comment]
I'm looking and I think I picked it up from https://github.com/pybind/cmake_example/blob/34f89ed216237660745ef39b127677fd89f876fe/setup.py#L37 and not from setuptools :facepalm:. I think what I actually want is the value of `build_ext.debug`.

**Comment by henryiii** [comment]
So I'll remove DEBUG, just need to decide if that's a patch or minor release type of a change.

I wonder if there's a way to support -C config-settings in setuptools mode (only if the setuptools wrapper backend is selected, of course). That would allow this to be set at the command line, rather than just env vars & pyproject.toml.

**Comment by dalcinl** [comment]
> I wonder if there's a way to support -C config-settings in setuptools mode 

Do you mean like the invocation below? Verbose, ugly, but definitely doable.

```
python -m build --wheel -C--global-option=build -C--global-option=--debug
```

**Comment by dalcinl** [comment]
> So I'll remove DEBUG, just need to decide if that's a patch or minor release type of a change.

What if you keep it, just in case, with maybe a deprecation warning? Then I guess no one would object to a patch release, as you would only break in case of `python -Werror`. In any case, I'm fine with it. My suggestion may not be worth the implementation trouble.

**Comment by henryiii** [comment]
> Do you mean like the invocation below? Verbose, ugly, but definitely doable.

I meant since we can intercept it, we could in theory pick out our options before passing on the rest to setuptools:

```bash
python -m build --wheel -Ccmake.build_type=Debug
```

> ```bash
> python -m build --wheel -C--global-option=build -C--global-option=--debug
> ```

We could pick up and respect `build.debug` if that's a thing.
