### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#517]
As the project grows I occasionally find use-cases where a dedicated cli might be useful e.g.:
- `skbuild-core version` to get the dynamic version
- `skbuild-core configure/build/install` perform the cmake/wheel commands manually
  This one I've noticed would be useful in packaging since the os packager might add system flags/options to be used, and it would be good to reuse those.

For the backend I am biased towards `click` so far especially for designing with sub-commands

**Comment by henryiii** [comment]
Yes, I've been planning to work on `scikit-build-cli` eventually. That would ideally happen around the time scikit-build's backend gets replaced by scikit-build-core.

**Comment by henryiii** [comment]
Work ongoing here: https://github.com/scikit-build/scikit-build-cli
