### ISSUE TITLE
Import issues with relative paths and editable install

### ISSUE THREAD

**Issue by ajoubertza** [scikit-build/scikit-build-core#532]
We've migrated our PyTango project to scikit-build-core - it has been working well, but the latest release has broken something with editable installs.

With 0.5.1, `pip install -e .` on Linux-based systems didn't work either, but it was a different issue.  Specifically, the compiled extension code, `_tango.so` in our case, had to be copied to back to the source repository folder to avoid a `ModuleNotFoundError: No module named 'tango._tango'` when importing our library.  More details in our [gitlab issue](https://gitlab.com/tango-controls/pytango/-/issues/556).  After copying the file, the import and library worked fine.  Interestingly, the file copying step isn't required on macOS (tested using mambaforge).

With 0.6.0, we don't get `ModuleNotFoundError: No module named 'tango._tango'` anymore,  Instead, there are many runtime warnings about objects in the extension code being re-registered have appeared, and then a new failure related to a relative import.

```pycon
>>> import tango
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for PyCmdDoneEvent already registered; second conversion method ignored.
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for PyAttrReadEvent already registered; second conversion method ignored.
...
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for log4tango::Level::LevelLevel already registered; second conversion method ignored.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/tango/__init__.py", line 451, in <module>
    from .attr_data import AttrData
  File "/app/tango/attr_data.py", line 26, in <module>
    from .utils import is_non_str_seq, is_pure_str
  File "/app/tango/utils.py", line 54, in <module>
    from .constants import AlrmValueNotSpec, StatusNotSet, TgLibVers
ModuleNotFoundError: No module named 'tango.attr_data.constants'
```

In our case, the `constants` module is imported from the compiled extension module earlier in `__init__.py`, so the code above worked previously.  Changing the imports above slightly, to import `constants` again fixed that problem, but then there was a new circular import problem in another module.

I guess it is related to changes in #399.  Maybe we have something incompatible in our code that needs to change.  I can provide the old and new `site-packages/_pytango_editable.py` files, if necessary.

P.S. Thanks for the great work on this project!

**Comment by LecrisUT** [comment]
Can you expand on
> In our case, the constants module is imported from the compiled extension module earlier in __init__.py, so the code above worked previously.

If you can run/mock a `tree` command to understand where are the cmake compiled modules and where are the python native modules. Also the last line in `_pytango_editable.py` would be helpful (if you can format it before pasting that would be wonderful)

**Comment by ajoubertza** [comment]
Sure.  For the constants import, in [`tango/__init__.py`](https://gitlab.com/tango-controls/pytango/-/blob/27c7d3af2ff71ba9ecf9eefe2df2154f3dae39da/tango/__init__.py#L422) is before import from local module `attr_data.py`.  This code worked fine with scikit-build-core 0.5.1 (and before we moved to scikit-build-core).

```
from ._tango import (
    ...
    constants,
    ...
)

from .attr_data import AttrData
```

<details><summary>Click to expand end of installation log</summary>

```
  [69/69] /opt/conda/bin/cmake -E cmake_symlink_library _tango.so.9.5.0.0  _tango.so.9 _tango.so && :

  *** Installing project into wheel...
  -- Install configuration: "Release"
  -- Installing: /tmp/tmpv5i74smf/wheel/platlib/tango/_tango.so.9.5.0.0
  -- Installing: /tmp/tmpv5i74smf/wheel/platlib/tango/_tango.so.9
  -- Installing: /tmp/tmpv5i74smf/wheel/platlib/tango/_tango.so
  *** Making editable...
  *** Created pytango-9.5.0.dev0-cp310-cp310-manylinux_2_36_aarch64.whl...
  Building editable for pytango (pyproject.toml) ... done
  Created wheel for pytango: filename=pytango-9.5.0.dev0-cp310-cp310-manylinux_2_36_aarch64.whl size=5519894 sha256=c16ea946ebffd8669583e5923105617ee4b69fdd99c52a205251ee5ea903921e
  Stored in directory: /tmp/pip-ephem-wheel-cache-1kxd14fg/wheels/9b/2c/d1/15e20a2b97f37ccf65a87ba1049c73a9076d0bf0fbaf814e83
Successfully built pytango
Installing collected packages: pytango
  Attempting uninstall: pytango
    Found existing installation: pytango 9.5.0.dev0
    Uninstalling pytango-9.5.0.dev0:
      Removing file or directory /opt/conda/lib/python3.10/site-packages/__pycache__/_pytango_editable.cpython-310.pyc
      Removing file or directory /opt/conda/lib/python3.10/site-packages/_pytango_editable.pth
      Removing file or directory /opt/conda/lib/python3.10/site-packages/_pytango_editable.py
      Removing file or directory /opt/conda/lib/python3.10/site-packages/pytango-9.5.0.dev0.dist-info/
      Removing file or directory /opt/conda/lib/python3.10/site-packages/tango/
      Successfully uninstalled pytango-9.5.0.dev0
Successfully installed pytango-9.5.0.dev0
```
</details>

<details><summary>Click to expand tree for site-packages and source repo</summary>

```
(base) mambauser@77cb6fcba93a:/opt/conda/lib/python3.10/site-packages/tango$ tree
.
├── _tango.so
├── _tango.so.9
└── _tango.so.9.5.0.0
```

Source code repo's root is in `/app`

```
(base) mambauser@77cb6fcba93a:/app$ tree
.
├── CMakeLists.txt
├── CMakePresets.json
├── CMakeUserPresets.json
├── LICENSE.txt
├── PyTango
│   └── __init__.py
├── README.rst
├── ext
│   ├── api_util.cpp
│   ├── archive_event_info.cpp
│   ...
├── pyproject.toml
├── tango
│   ├── __init__.py
│   ├── api_util.py
│   ├── asyncio.py
│   ├── asyncio_executor.py
│   ├── attr_data.py
│   ...
└── tests
    ├── conftest.py
...
```
</details>

<details><summary>Click to expand for last line in _pytango_editable.py  </summary>

```
install({
    'tango': '/app/tango/__init__.py',
    'tango.api_util': '/app/tango/api_util.py',
    'tango.asyncio': '/app/tango/asyncio.py',
    'tango.asyncio_executor': '/app/tango/asyncio_executor.py',
    'tango.attr_data': '/app/tango/attr_data.py',
    'tango.attribute_proxy': '/app/tango/attribute_proxy.py',
    'tango.auto_monitor': '/app/tango/auto_monitor.py',
    'tango.base_types': '/app/tango/base_types.py',
    'tango.callback': '/app/tango/callback.py',
    'tango.client': '/app/tango/client.py',
    'tango.codec': '/app/tango/codec.py',
    'tango.connection': '/app/tango/connection.py',
    'tango.db': '/app/tango/db.py',
    'tango.device_attribute': '/app/tango/device_attribute.py',
    'tango.device_class': '/app/tango/device_class.py',
    'tango.device_data': '/app/tango/device_data.py',
    'tango.device_proxy': '/app/tango/device_proxy.py',
    'tango.device_server': '/app/tango/device_server.py',
    'tango.encoded_attribute': '/app/tango/encoded_attribute.py',
    'tango.exception': '/app/tango/exception.py',
    'tango.futures': '/app/tango/futures.py',
    'tango.futures_executor': '/app/tango/futures_executor.py',
    'tango.gevent': '/app/tango/gevent.py',
    'tango.gevent_executor': '/app/tango/gevent_executor.py',
    'tango.globals': '/app/tango/globals.py',
    'tango.green': '/app/tango/green.py',
    'tango.group': '/app/tango/group.py',
    'tango.group_reply': '/app/tango/group_reply.py',
    'tango.group_reply_list': '/app/tango/group_reply_list.py',
    'tango.log4tango': '/app/tango/log4tango.py',
    'tango.pipe': '/app/tango/pipe.py',
    'tango.pipe_data': '/app/tango/pipe_data.py',
    'tango.pytango_init': '/app/tango/pytango_init.py',
    'tango.pytango_pprint': '/app/tango/pytango_pprint.py',
    'tango.pyutil': '/app/tango/pyutil.py',
    'tango.release': '/app/tango/release.py',
    'tango.server': '/app/tango/server.py',
    'tango.tango_numpy': '/app/tango/tango_numpy.py',
    'tango.tango_object': '/app/tango/tango_object.py',
    'tango.test_context': '/app/tango/test_context.py',
    'tango.test_utils': '/app/tango/test_utils.py',
    'tango.time_val': '/app/tango/time_val.py',
    'tango.utils': '/app/tango/utils.py',
    'tango.databaseds.DataBase': '/app/tango/databaseds/DataBase.xmi',
    'tango.databaseds.DataBaseds': '/app/tango/databaseds/DataBaseds',
    'tango.databaseds': '/app/tango/databaseds/__init__.py',
    'tango.databaseds.create_db': '/app/tango/databaseds/create_db.sql',
    'tango.databaseds.create_db_tables': '/app/tango/databaseds/create_db_tables.sql',
    'tango.databaseds.database': '/app/tango/databaseds/database.py',
    'tango.databaseds.db_errors': '/app/tango/databaseds/db_errors.py',
    'tango.databaseds.mysql2sqlite': '/app/tango/databaseds/mysql2sqlite.sh',
    'tango.databaseds.tango_database': '/app/tango/databaseds/tango_database.db',
    'tango.databaseds.db_access': '/app/tango/databaseds/db_access/__init__.py',
    'tango.databaseds.db_access.sqlite3': '/app/tango/databaseds/db_access/sqlite3.py',
    'PyTango': '/app/PyTango/__init__.py'
},
{
    'tango._tango': 'tango/_tango.so.9.5.0.0'
}, None, False, True,
[
    '-v'
],
[])
```
</details>

**Comment by LecrisUT** [comment]
Can you give an update of the error you are getting? I don't see where `tango.attr_data.constants` would be called from in the commit you are currently on. Everything looks fine except that `tango.attr_data` is a module, not a package, so you shouldn't be able to navigate to any "module" deeper than that. But on the other hand, I do not see anything that would be providing `tango.attr_data.constants` module, or what would be consuming it as `tango.attr_data.constants` instead of `tango.constants` can you clarify that? Also, is `constants` a module or a `class`? Maybe there was a typo somewhere?

**Comment by ajoubertza** [comment]
The `constants` is a module exported by the extension code (using Boost.Python).  The  code is in [`ext/constants.cpp`](https://gitlab.com/tango-controls/pytango/-/blob/27c7d3af2ff71ba9ecf9eefe2df2154f3dae39da/ext/constants.cpp#L94).   In `tango/__init__.py` we import the `constants` module from the extension module `_tango.so`. 

The `tango.attr_data.constants`  shouldn't be used anywhere, and wasn't.  The original error is at line 54 of `tango/utils.py`, (which is imported from `tango/attr_data.py`).  In `utils.py` we are trying to import some values from the compiled `constants` module:  `from .constants import AlrmValueNotSpec, StatusNotSet, TgLibVers`.   This should be referencing the `constants` imported in `__init__.py`, but now it incorrectly uses the `attr_data` namespace. 

I previously tried removing that line, and using `from _tango import constants` instead.  Then use things like `constants.AlrmValueNotSpec`.  This just caused problems in another place (circular import error).
 

Any ideas about the new runtime warnings, like  `<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for PyCmdDoneEvent already registered; second conversion method ignored.`?  That wasn't happening in version 0.5.1, so maybe it is a clue.

**Comment by burgholzer** [comment]
Maybe it helps: We are also experiencing similar issues over at https://github.com/cda-tum/mqt-core/actions/runs/6615902164/job/17969326394.
```console
__________________________________________________________________________________ ERROR collecting test/python/test_qiskit.py ___________________________________________________________________________________
ImportError while importing test module '/Users/burgholzer/CLionProjects/mqt-core-2/test/python/test_qiskit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/python/test_qiskit.py:12: in <module>
    from mqt.core.operations import CompoundOperation, SymbolicOperation
src/mqt/core/__init__.py:5: in <module>
    from . import operations, symbolic
src/mqt/core/symbolic.py:5: in <module>
    from ._core.symbolic import Expression, Term, Variable
E   ImportError: generic_type: type "Permutation" is already registered!
```

I can confirm that downgrading to `<0.6` as well as non-editable installs resolve the error on our side.
Code is living here: https://github.com/cda-tum/mqt-core
Scikit-build-core config: https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/pyproject.toml#L70-L108
CMake file for the pybind11 extension module: https://github.com/cda-tum/mqt-core/blob/main/src/python/CMakeLists.txt

**Comment by henryiii** [comment]
Unrelated: pybind11 or nanobind? Pybind11 doesn't set support Stable ABI / Limited API (though it should be possible for CPython 3.12+), so https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/pyproject.toml#L84-L85 shouldn't work with pybind11 on CPython 3.12+ (yet).

**Comment by henryiii** [comment]
Also, are you coping any files around, like the OP, or is that "out of the box" behavior?

**Comment by burgholzer** [comment]
> Unrelated: pybind11 or nanobind? Pybind11 doesn't set support Stable ABI / Limited API (though it should be possible for CPython 3.12+), so https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/pyproject.toml#L84-L85 shouldn't work with pybind11 on CPython 3.12+ (yet).

We use `pybind11` for now.
Maybe I am misinterpreting the output, but https://github.com/cda-tum/mqt-core/actions/runs/6518458808/job/17703904054 seems to suggest that cibuildwheel is producing a `abi3` wheel for Python 3.12.
So I figured it is working as intended. Maybe I am wrong though.

> Also, are you coping any files around, like the OP, or is that "out of the box" behavior?

I am not copying any files around. The only part where I am setting some kind of path is in the `install` command here:
https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/CMakeLists.txt#L65-L66

Might namespace packages create some trouble here?

**Comment by henryiii** [comment]
Pybind11 isn't compatible with ABI3 yet, at least as far as I know. I'm guessing you aren't defining `Py_LIMITED_API` before importing Python/pybind11, as so you are making normal wheels, and just calling them ABI3. (That's a guess, though).

Namespace packages probably do cause trouble. Let's see what we can find, this project looks a bit easier to debug, since it's pybind11 instead of Boost::Python, and no copying is needed.

We might need to gate the change in #399 as an experimental mode.

**Comment by LecrisUT** [comment]
In both cases there seems to be a sub-module that is trying to be exposed `from ._core.symbolic import Expression, Term, Variable`. In this case the link to the cmake compiled module seems to have worked, but it is encountering a different issue with the module double-loading. It is curious that these are popping up now. The only significant part we altered was to add `submodule_search_locations`, which shouldn't have changed how the cmake built libraries are loaded :thinking:

**Comment by ajoubertza** [comment]
@LecrisUT I tried the proposed changes, but no luck.

```diff
diff --git a/ext/constants.cpp b/ext/constants.cpp
index 5b56de4..2b184de 100644
--- a/ext/constants.cpp
+++ b/ext/constants.cpp
@@ -91,7 +91,7 @@ static void export_optional_constants(scope& consts_scope)

 void export_constants()
 {
-    object consts_module(handle<>(borrowed(PyImport_AddModule("tango.constants"))));
+    object consts_module(handle<>(borrowed(PyImport_AddModule("tango._tango.constants"))));
     scope().attr("constants") = consts_module;
     scope consts_scope = consts_module;
```

On its own, no change.  Still get `ModuleNotFoundError: No module named 'tango.attr_data.constants'`.

Changing `_pytango_editable.py` made no difference (if I did it the right way...):

```diff
(base) mambauser@77cb6fcba93a:/$ diff /tmp/_pytango_editable.py.orig /opt/conda/lib/python3.10/site-packages/_pytango_editable.py
255c255,258
<     {"tango._tango": "tango/_tango.so.9.5.0.0"},
---
>     {
>         "tango._tango": "tango/_tango.so.9.5.0.0",
>         "tango._tango.constants": "tango/_tango.so.9.5.0.0",
>     },
```

**Comment by burgholzer** [comment]
> Pybind11 isn't compatible with ABI3 yet, at least as far as I know. I'm guessing you aren't defining `Py_LIMITED_API` before importing Python/pybind11, as so you are making normal wheels, and just calling them ABI3. It will work fine until you try to load it on CPython 3.13, where it will probably segfault or something. (That's a guess, though).

I am fairly sure you are right. The only lines regarding the limited ABI we have in the project are 
https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/CMakeLists.txt#L35-L38
and 
https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/CMakeLists.txt#L39-L44

I guess we will see once the Python 3.13 betas/release candidates come around.

> Namespace packages probably do cause trouble. Let's see what we can find, this project looks a bit easier to debug, since it's pybind11 instead of Boost::Python, and no copying is needed.
> 
> We might need to gate the change in #399 as an experimental mode.

Maybe it's also worth to cross-reference https://github.com/wjakob/nanobind_example/issues/30, where some discussion regarding editable installs was going on (although based on nanobind, we found the same considerations apply for pybind11 extensions).

**Comment by LecrisUT** [comment]
> `ModuleNotFoundError: No module named 'tango.attr_data.constants'`

The source of this issue is weird, I don't get why it is pointing to `tango.attr_data.` instead of `tango.`. Can you use absolute path for where `constants` is called to rule out this particular issue? This seems like a python issue?

@burgholzer for your issue, is the syntax using `PYBIND11_MODULE` correct here?
https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/module.cpp#L14C8-L18

Is there an equivalent that defines a package instead of a module? If I am reading the errors correctly it seems the issue is that `._core.symbolic` is loaded multiple times (maybe once from `._core` and again from `._core.symbolic`) with the second time trying to create the module again.

@henryiii Are the API for navigating compiled packages correct in both cases?

**Comment by burgholzer** [comment]
> @burgholzer for your issue, is the syntax using `PYBIND11_MODULE` correct here? https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/module.cpp#L14C8-L18

That macro is _the_ entry point for a pybind11 extension; see https://pybind11.readthedocs.io/en/stable/reference.html#c.PYBIND11_MODULE
 
> Is there an equivalent that defines a package instead of a module? If I am reading the errors correctly it seems the issue is that `._core.symbolic` is loaded multiple times (maybe once from `._core` and again from `._core.symbolic`) with the second time trying to create the module again. Maybe when we did not set `submodule_search_locations`, it was not able to navigate further down and it was using some cached value, but now that we have "fixed it" these issues are being picked up? These issue seem to be persistent with all python versions as well (not sure about 3.12)

I can confirm that the issue is persistent from Python 3.8-3.12 under all major operating systems.
I am not quite sure the `.symbolic` import has anything to do with this. The error
> ImportError: generic_type: type "Permutation" is already registered!

Is completely independent from the `symbolic` submodule as the permutation submodule is already bound here: https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/module.cpp#L15 and does not at all use or refer to the `Permutation` class.

**Comment by LecrisUT** [comment]
> > @burgholzer for your issue, is the syntax using `PYBIND11_MODULE` correct here? https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/module.cpp#L14C8-L18
> 
> That macro is _the_ entry point for a pybind11 extension; see https://pybind11.readthedocs.io/en/stable/reference.html#c.PYBIND11_MODULE
> 
> > Is there an equivalent that defines a package instead of a module? If I am reading the errors correctly it seems the issue is that `._core.symbolic` is loaded multiple times (maybe once from `._core` and again from `._core.symbolic`) with the second time trying to create the module again. Maybe when we did not set `submodule_search_locations`, it was not able to navigate further down and it was using some cached value, but now that we have "fixed it" these issues are being picked up? These issue seem to be persistent with all python versions as well (not sure about 3.12)
> 
> I can confirm that the issue is persistent from Python 3.8-3.12 under all major operating systems. I am not quite sure the `.symbolic` import has anything to do with this. The error
> 
> > ImportError: generic_type: type "Permutation" is already registered!
> 
> Is completely independent from the `symbolic` submodule as the permutation submodule is already bound here: https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/module.cpp#L15 and does not at all use or refer to the `Permutation` class.

My suspicion is that when it loads `._core` it registers `class Permutation` as `._core.Permutation`, it goes through to define `._core.symbolic`, and other submodules. Then when it is trying to navigate one level further, it goes through `_core.so` again (because it would be searching in all the places where `_core` package is defined), trying to register `class Permutation` again. Does changing the order of `registerPermutation(m);` have any effect?

**Comment by burgholzer** [comment]
> My suspicion is that when it loads `._core` it registers `class Permutation` as `._core.Permutation`, then it goes through to define `._core.symbolic`, and other submodules. Then when it is trying to navigate one level further, it goes through `_core.so` again (because it would be searching in all the places where `_core` package is defined), trying to register `class Permutation` again. Does changing the order of `registerPermutation(m);` have any effect?
> 
> @burgholzer Do you see a way to gate [this snippet](https://github.com/cda-tum/mqt-core/blob/a1630ea2ddbeb89ef28e433b106880a9d9f3e343/src/python/register_permutation.cpp#L7-L9) with an `if defined` to avoid the double initialization? This would not fix the underlying problem, but it could give us a clue further down as to why it is trying to load and register the `.so` file twice.

I can try something like that tomorrow. Although I would be surprised if such guards are necessary. The library structure is heavily inspired by https://github.com/scikit-hep/boost-histogram and I do not see any definition guards in the submodule registration files there.

What I just tried was merely building the `mqt.core` package with
```c++
PYBIND11_MODULE(_core, m) {
  py::module symbolic = m.def_submodule("symbolic");
  registerSymbolic(symbolic);

//  registerPermutation(m);

  py::module operations = m.def_submodule("operations");
  registerOperations(operations);

//  registerQuantumComputation(m);
}
```
the error shifts to
```console
ImportError while importing test module '/Users/burgholzer/CLionProjects/mqt-core-2/test/python/test_qiskit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/python/test_qiskit.py:12: in <module>
    from mqt.core.operations import CompoundOperation, SymbolicOperation
src/mqt/core/__init__.py:5: in <module>
    from . import operations, symbolic
src/mqt/core/symbolic.py:5: in <module>
    from ._core.symbolic import Expression, Term, Variable
E   ImportError: generic_type: type "Variable" is already registered!
```
which is the same underlying problem.

**Comment by LecrisUT** [comment]
> ```c++
> PYBIND11_MODULE(_core, m) {
>   py::module symbolic = m.def_submodule("symbolic");
>   registerSymbolic(symbolic);
> 
> //  registerPermutation(m);
> 
>   py::module operations = m.def_submodule("operations");
>   registerOperations(operations);
> 
> //  registerQuantumComputation(m);
> }
> ```
> 
> the error shifts to

Thanks that is actually helpful because it is slightly different. At that point it should be aware that it is navigating `._core.symbolic`, but it still tries to register the variable again.

> I can try something like that tomorrow. Although I would be surprised if such guards are necessary. The library structure is heavily inspired by https://github.com/scikit-hep/boost-histogram and I do not see any definition guards in the submodule registration files there.

Indeed the core issue is that it is going through the `.so` library trying to register everything again. If I understand this issue correctly, if you make `_core.symbolic` a differenc library, this issue should not be triggered in `symbolic` anymore.

I am looking at `meson`'s implementation again:
https://github.com/mesonbuild/meson-python/blob/962585e3068e2f7f813167c0bbaad11c6838dc0f/mesonpy/_editable.py#L186C25-L186C25

They are stripping the `submodule_search_locations`, and instead they are relying on custom loaders to navigate. I wonder if there is something in the python's default loader of `.so` that creates these issues and why they didn't go that route.

On our side, we could expand the test case: https://github.com/scikit-build/scikit-build-core/tree/main/tests/packages/navigate_editable to navigate further down and investigate those issues

**Comment by ajoubertza** [comment]
@LecrisUT 

> The source of this issue is weird, I don't get why it is pointing to `tango.attr_data`. instead of `tango.`. Can you use absolute path for where `constants` is called to rule out this particular issue? This seems like a python issue?

I agree it is weird, but isn't it the weird importlib redirection from `ScikitBuildRedirectingFinder` that is more likely the culprit than CPython?  Maybe a silly question, but why can't the installer just put the .so files into the source folder (like our old setuptools approach did) instead of putting them in `site-packages` and doing all the importlib magic?

Change below:

```diff
diff --git a/tango/utils.py b/tango/utils.py
index cc90c32..c373997 100644
--- a/tango/utils.py
+++ b/tango/utils.py
@@ -48,10 +48,10 @@ from ._tango import (
     DevIntrChangeEventData,
     Database,
     EncodedAttribute,
+    constants,
 )

 from . import _tango
-from .constants import AlrmValueNotSpec, StatusNotSet, TgLibVers
 from .release import Release

 __all__ = (
@@ -254,7 +254,7 @@ for k, v in TO_TANGO_TYPE.items():
     if v in _scalar_to_array_type:
         _scalar_to_array_type[k] = _scalar_to_array_type[v]

-__NO_STR_VALUE = AlrmValueNotSpec, StatusNotSet
+__NO_STR_VALUE = constants.AlrmValueNotSpec, constants.StatusNotSet

 __device_classes = None

@@ -271,7 +271,7 @@ def __requires(package_name, min_version=None, conflicts=(), software_name="Soft
     if package_name_l == "pytango":
         curr_version = Version(Release.version)
     elif package_name_l == "tango":
-        curr_version = Version(TgLibVers)
+        curr_version = Version(constants.TgLibVers)
     else:
         try:
             package = __import(package_name)
```

After this, `import tango` works, as mentioned in the original issue description, but then some of the other module imports break, e.g. with `import tango.test_utils`:

```
>>> import tango
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for PyCmdDoneEvent already registered; second conversion method ignored.
...
<frozen importlib._bootstrap>:241: RuntimeWarning: to-Python converter for log4tango::Level::LevelLevel already registered; second conversion method ignored.
>>> import tango.test_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/tango/test_utils.py", line 9, in <module>
    from . import DevState, GreenMode, AttrDataFormat, ExtractAs
ImportError: cannot import name 'DevState' from partially initialized module 'tango.test_utils' (most likely due to a circular import) (/app/tango/test_utils.py)
>>>
```

The `DevState` class is also from the extension code, `tango._tango.DevState`.

**Comment by LecrisUT** [comment]
> Maybe a silly question, but why can't the installer just put the .so files into the source folder (like our old setuptools approach did) instead of putting them in `site-packages` and doing all the importlib magic?

CMake in general is made to build in separate build directory. If we put it in the source folder, it would break the ability to have multiple builds. Ideally they wouldn't be in `site-packages` either, and instead they would be in the build directory, but we haven't started to work on that yet (seems we have more fundamental issues to solve here).

Did changing with absolute path not work?
```diff
- from .constants import AlrmValueNotSpec, StatusNotSet, TgLibVers
+ from tango.constants import AlrmValueNotSpec, StatusNotSet, TgLibVers
```

**Comment by henryiii** [comment]
I do plan to have a `inplace` mode eventually, which would do exactly that (but would break multiple builds, etc, as usual - but is it something we can do that meson can't). That's one of the reasons we have a mode setting (that currently supports only one mode).

**Comment by dialecticDolt** [comment]
In case it helps, I also ran into this (or a closely related issue) when porting/testing a Cython library to use scikit-build-core. 
For me the minimal reproducer (using only pure python) seems to be:
 https://github.com/dialecticDolt/skbuild-core-import/tree/nocython

**Comment by ajoubertza** [comment]
> Did changing with absolute path not work?

Aah, now I see what you mean.  Yes, using `from tango.constants import AlrmValueNotSpec, StatusNotSet, TgLibVers` also works, if I revert the change in `constants.cpp`, and go back to `PyImport_AddModule("tango.constants")`.  By "works", I mean I can `import tango`.  I still get all the runtime warnings about re-registering things, and I still have the circular import issue with other modules.  I can try changing all the relative imports to absolute, and see if that helps.

> CMake in general is made to build in separate build directory. If we put it in the source folder, it would break the ability to have multiple builds

Having multiple builds in different build directories is great, so recompilation is quicker.  However, even if we have multiple builds available, only one can be installed at a time.  How about copying the compiled files (i.e., `tango.so`) from the build dir to the source dir at the end of the installation process?  If the developer pip installs with using a different `--build-dir` then the old files get removed from the source dir, and new files get copied in.  Nothing has to go in `site-packages.  Maybe that is already your plan.

**Comment by Simon-Lopez** [comment]
Just like @dialecticDolt, if it helps...

I ran into the bug using nanobind (1.6.2) and created a minimal reproducer modifying the nanobind_example from @wjakob 
I can confirm that using absolute import in src/nanobind_example/nested.py solves the problem.

Cf the fork at: https://github.com/Simon-Lopez/nanobind_example

Installation with:
```
python -m pip install --no-build-isolation -ve . -Ceditable.rebuild=true
```

The error is triggered with:

```
python -c "import nanobind_example"
```

**Comment by LecrisUT** [comment]
I have @dialecticDolt example implemented in #535 if anyone can add more there. The example of @ajoubertza and @burgholzer are a bit different and I need to implement those. I think we can only address the multi-import error there if we can write the minimal example reproducibly there. The difference in absolute vs relative path in @ajoubertza could be the same as @dialecticDolt example, let's see if we can reproduce it there.

**Comment by ajoubertza** [comment]
@LecrisUT After changing all the relative imports to absolute (except in `tango/__init__.py`) it works correctly.  No runtime warnings about re-registering things, and no circular import problems.

I guess that narrows the issue down to relative imports and some change in version 0.6.0.

I don't mind changing all our relative imports to absolute, so this issue is resolved from my point of view.  Up to you if you want to try to restore the functionality with relative imports.

**Comment by njzjz** [comment]
I got this error when I tried to bump scikit-build-core to 0.6.0:

```
 /opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
source/tests/test_virtual_type.py:7: in <module>
    from common import (
source/tests/common.py:12: in <module>
    from deepmd.entrypoints.main import (
deepmd/__init__.py:13: in <module>
    from . import (
deepmd/fit/__init__.py:8: in <module>
    from .ener import (
deepmd/fit/ener.py:24: in <module>
    from deepmd.infer import (
deepmd/infer/__init__.py:37: in <module>
    from .model_devi import (
deepmd/infer/model_devi.py:14: in <module>
    from ..utils.batch_size import (
E   ModuleNotFoundError: No module named 'deepmd.infer.utils'
```

When using `from ..utils` in the `deepmd.infer` module, it tries to find `deepmd.infer.utils` instead of `deepmd.utils`.

**Comment by henryiii** [comment]
I'm looking into fixing this.
