### ISSUE TITLE
sdist: Wrong capitalization in "Author-email" metadata key

### ISSUE THREAD

**Issue by dalcinl** [scikit-build/scikit-build-core#541]
Source distribution metadata (`PKG-INFO` file) as generated by skbuild contains a key `Author-Email`, however the [specification](https://packaging.python.org/en/latest/specifications/core-metadata/#author-email) says the key should be capitalized as `Author-email`.  

To skbuild's defense, it is very unfortunate that `Author-email` and `Maintainer-email` break the rules respect to all the other double-word keys in the spec. FWIW, Setuptools follows the spec. Maybe this issue is ultimately inconsequential, but just in case I'm reporting it here.

PS: Another difference respect to setuptools: setuptools generates a `License-File` field, although this field is not mentioned in the spec. I'm still investigating whether this skbuild vs setuptools difference I'm seeing may be my fault.

**Comment by LecrisUT** [comment]
Worth comparing with `hatch`, `poetry`, and `flit`. Also curious how some that generally went against the PEP standards like `pbr`.

**Comment by henryiii** [comment]
This would be an issue with pyproject-metadata, and at least pdm-backend and meson-python use that too.

**Comment by henryiii** [comment]
Setuptools implements an old version of the unaccepted PEP 639. That’s why it has `License-File`.

**Comment by henryiii** [comment]
Would you like to open an issue at https://github.com/FFY00/python-pyproject-metadata/issues (still might be me that fields it, but better organized that way. ;) )

**Comment by dalcinl** [comment]
cf. FFY00/python-pyproject-metadata#71

**Comment by henryiii** [comment]
It's actually valid since the is based on the case-insensitive email spec.
