### ISSUE TITLE
getting "libpython3.8.a is not a real file" under cibuildwheel on Linux 

### ISSUE THREAD

**Issue by wojdyr** [scikit-build/scikit-build-core#570]
I want to ask if it rings a bell. I started using scikit-build-core a couple months ago. It works in all configurations I tested it, except when I try to build wheels with cibuildwheel. In this one case I get such an error on Linux:
```
    *** scikit-build-core 0.7.0 using CMake 3.27.6 (wheel)
    *** Configuring CMake...
    2023-12-12 19:26:59,378 - scikit_build_core - WARNING - libdir/ldlibrary: /opt/_internal/cpython-3.8.18/lib/libpython3.8.a is not a real file!
    2023-12-12 19:26:59,378 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/opt/_internal/cpython-3.8.18/lib, ldlibrary=libpython3.8.a, multiarch=x86_64-linux-gnu, masd=None
    loading initial cache file /tmp/tmpc259wp2k/build/CMakeInit.txt
    -- The C compiler identification is GNU 10.2.1
    -- The CXX compiler identification is GNU 10.2.1
 [...]
    CMake Error at /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
      Could NOT find Python (missing: Python_LIBRARIES Interpreter Development
      Development.Module Development.Embed) (found version "3.8.18")
    Call Stack (most recent call first):
      /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
      /opt/_internal/pipx/venvs/cmake/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/FindPython.cmake:616 (find_package_handle_standard_args)
      CMakeLists.txt:401 (find_package)
```

I get the same both locally and in GitHub actions:
https://github.com/project-gemmi/gemmi/actions/runs/7186325507/job/19571479774#step:3:313
Tried using older scikit-build-core, older cibuildwheel, different python version, but doesn't make a difference. Except that when building with a different python version I get different file in the output:

    2023-12-12 20:33:34,762 - scikit_build_core - WARNING - libdir/ldlibrary: /opt/_internal/cpython-3.10.13/lib/libpython3.10.a is not a real file!

**Comment by henryiii** [comment]
You were trying to include the “Embed” target, which looks for the static library. that’s not supported in manylinux, which is only designed for making wheels, which should never link to Python statically.

If you change the search to look for just the Development.Module (and Interpreter) components, you’ll be fine (unless you really are making an app that doesn’t run from Python, and instead embeds Python).

**Comment by wojdyr** [comment]
Thanks! That was it.
I was specifying component `Development` (without `.Module`), so that it can be used from CMake < 3.18 outside of scikit-build-core. I didn't realize this was causing the problem.
