### ISSUE TITLE
Unwanted file when building sdist.

### ISSUE THREAD

**Issue by hzhangxyz** [scikit-build/scikit-build-core#577]
Based on the first pybind11 example in https://scikit-build-core.readthedocs.io/en/latest/getting_started.html.

I add `wheel.packages = []` in `[tool.scikit-build]` and add some meaningless python file in the project root directory. When I invoke `python -m build .`, the result sdist contains all these meaningless python file.

What is expected is that, automatical package finding is disable by `wheel.packages`.

**Comment by LecrisUT** [comment]
Do you mean `wheel` or `sdist`? The latter by default is basically just the git archive + metadata files

**Comment by hzhangxyz** [comment]
> Do you mean `wheel` or `sdist`? The latter by default is basically just the git archive + metadata files, regardless of what python packages you include in `wheel`

As what I said, I means sdist, not the wheel. Yes, sdist is only grouping of source code, but for now, scikit-build-core groups the unexpected files.

**Comment by henryiii** [comment]
`wheel.packages` doesn't affect the SDist. Notice it has "wheel." in it. ;) The SDist is supposed to contain things the wheel doesn't (tests, pyprojec.toml, etc). By default, the SDist is basically like `git archive`. You can add files/patterns you want explicitly to exclude to `sdist.exclude`.

**Comment by henryiii** [comment]
And you can `sdist.exclude = ["*"]` + `sdist.include = [...]` to fully control the SDist contents. Otherwise, the exclude list is the `.gitignore` plus this exclude list, just like hatchling.

**Comment by hzhangxyz** [comment]
Thanks for you reply, which solves my problem now.

But I still think there is definitely something wrong. In the default behavior, even `dist` will be included in the second times sdist result after the first built which generate first sdist in folder `dist`.

**Comment by LecrisUT** [comment]
Make sure you have `.gitignore` setup. Although are we using `git archive` explicitly? That might be necessary with the `DynamicVersion` CMake module.

**Comment by hzhangxyz** [comment]
@LecrisUT  I have `dist` in `.gitignore`, but `.gitignore` is placed in the parent folder of this python project root folder. My repo structure is something like

```
ROOT
|- .gitignore
|- ThisPythonProject
|  |- CMakeLists.txt
|  |- pyproject.toml
|  |- ...
|- ...
```

**Comment by hzhangxyz** [comment]
For other backend such as `setuptools`, it includes files in sdist negatively, it only includes common files such as `setup.py`, `pyproject.toml`, `README.md` into sdist by default. Any file it does not know about is excluded, unless they are specified in `MANIFEST.in`.

But for scikit-build-core, it includes files positively, it seems it want include all the files it does not know about, even a `*.js` file in my folder is included by default, although I want it indeed.

**Comment by hzhangxyz** [comment]
Closed first since my problem has been solved indeed, although I think current behavior is strange.

**Comment by LecrisUT** [comment]
Current behavior is similar for hatchling, and in general having it be a superset of `git archive` is preferred for packaging since the canonical standard is to use the PyPI sdist, and the tests, docs, examples should be included for packaging
