### ISSUE TITLE
Combining python code with C++ bindings

### ISSUE THREAD

**Issue by dudoslav** [scikit-build/scikit-build-core#582]
When using python wrapper with pybind11 binding with these steps:

1. Building bindings (CMAKE)
2. Installing bindings into `src/package/` (CMAKE)
3. I assume package export (SCIKIT_BUILD_CORE)

The bindings `.so` file gets ignored. I am currently working on an open source project that tries to use `scikit-build-core`: https://github.com/dudoslav/TileDB-Vector-Search/blob/db/sc-38439/scikit_build_core/pyproject.toml

When I run `pipx run build` I can see that proper files get installed:
```
...
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/include/experimental/mdarray
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/include/experimental/mdspan
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/include/mdspan
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/include/mdspan/mdspan.hpp
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/include/mdspan/mdarray.hpp
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/lib/cmake/mdspan/mdspanConfig.cmake
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/lib/cmake/mdspan/mdspanConfigVersion.cmake
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/./_tiledbvspy.cpython-310-x86_64-linux-gnu.so
-- Set runtime path of "/tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/./_tiledbvspy.cpython-310-x86_64-linux-gnu.so" to "$ORIGIN/lib"
-- Installing: /tmp/build-via-sdist-21j8td_0/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220/apis/python/src/tiledb/vector_search/lib/libtiledb.so.2.18
*** Installing project into wheel...
-- Install configuration: "Release"
*** Making wheel...
*** Created tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220-cp310-cp310-manylinux_2_35_x86_64.whl...
Successfully built tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220.tar.gz and tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220-cp310-cp310-manylinux_2_35_x86_64.whl
```

but when inspecting the wheel (`unzip -l dist/tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220-cp310-cp310-manylinux_2_35_x86_64.whl `) I can not find that pybind .so file:
```
...
     2303  2023-12-20 16:14   tiledb/vector_search/lib/cmake/mdspan/mdspanConfigVersion.cmake
     4046  2023-12-20 16:14   tiledb/vector_search/lib/cmake/mdspan/mdspanTargets.cmake
 26958440  2023-12-20 16:14   tiledb/vector_search/lib/libtiledb.so.2.18
      403  2023-12-20 16:14   tiledb/vector_search/lib/pkgconfig/docopt.pc
    21499  2023-12-20 16:14   tiledb/vector_search/module.cc
    11839  2023-12-20 16:14   tiledb/vector_search/module.py
     2046  2023-12-20 16:14   tiledb/vector_search/storage_formats.py
     1381  2023-12-20 16:14   tiledb/vector_search/utils.py
     3215  2023-12-20 16:14   tiledb_vector_search-0.0.20.dev9+g51afa59.d20231220.dist-info/METADATA
```

**Comment by dudoslav** [comment]
To be more specific, my question is: "What files are included in wheel from the build folder?"

**Comment by LecrisUT** [comment]
I tried to look at it and find some configuration issues, but I couldn't see anything relevant. My only suspicion was with `CMAKE_INSTALL_PREFIX`, but then you show that `lib` directory is indeed installed, which is what confuses me.

From what I am aware of, and probably @henryiii will clarify things later:
- All python files from `tool.scikit-build.wheel.packages` are installed from the source folders. Installed files do not need to be there
- CMake installed files are installed in-place from the `.` install path. Think of it as you would copy all of those files in the `site_packages`, that folder structure will be preserved. To install other files you might need to change the install path according to https://scikit-build-core.readthedocs.io/en/latest/cmakelists.html#install-directories

Sorry I can't help more with this one. I am also confused about the results

**Comment by dudoslav** [comment]
No problem sir, after some digging I decided to use ${SCIKIT_PLATLIB_DIR} as CMAKE_INSTALL_PREFIX and it kind of works now :)

**Comment by dudoslav** [comment]
I just wasn't sure if there was a way to specify what files should be copied into wheel inside of the pyproject file

**Comment by LecrisUT** [comment]
If you want to walk me through your project's current design, I can give a review of it and suggest some simplifications. At first glance, I believe there is an issue with the design of `SUPERBUILD`, and it can be greatly simplified using `FetchContent`, but I would need some guidance on what is the intent of that design, requirements etc.

**Comment by dudoslav** [comment]
Ah, you have a good eye. Most of our build issues stem from the `SUPERBUILD` issues :D . We plan to rework the whole build system after new year, so there is no point in fixing this any further. But the `SUPERBUILD` must go, its unmaintanable.
