### ISSUE TITLE
[Fedora:rawhide] Failures in hash checks

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#596]
Seems we have some tests failing on `rawhide`: https://copr.fedorainfracloud.org/coprs/g/scikit-build/release/build/6843074/

`test_pep517_sdist_time_hash_set_epoch` and `test_pep517_sdist_hash`. All of them seem to involve `SOURCE_DATE_EPOCH`, but that variable is still set. I am wondering if a different variable takes precedence now? If it's a similar issue that was solved before, I guess running the tests in a container should pass, while the rpm build should fail. I'll try that quickly

**Comment by henryiii** [comment]
I was guessing that there might have been a patch applied to something (probably pyproject-metadata) that is affecting us.

**Comment by LecrisUT** [comment]
Indeed that might be the more probable cause. I just ran it on the rawhide container and it failed with the same sha, so it is reproducible at least

**Comment by LecrisUT** [comment]
Here are the [rawhide](https://github.com/scikit-build/scikit-build-core/files/13805605/cmake_example-0.0.1.tar.gz) and [f39](https://github.com/scikit-build/scikit-build-core/files/13805607/cmake_example-0.0.1.tar.gz) sdist generated files for comparison. Bitwise the content doesn't seem to differ, so it might be just the tar operation. I've also realized that I have ran with `pip install` in both cases, so it is something specific to a base Fedora package.
