### ISSUE TITLE
Support for version suffix

### ISSUE THREAD

**Issue by jonyscathe** [scikit-build/scikit-build-core#607]
Hi,
I am trying to publish a modified python package to a private repository.
As per PEP440 conventions I want to add a local suffix (in my case +local0).
https://peps.python.org/pep-0440/#local-version-identifiers

However, if I do this I get:
```
CMake Error at CMakeLists.txt:5 (project):
  VERSION "0.12.4+local0" format invalid.
```

I understand CMake only supports `major.minor[.patch[.tweak]]` versioning so does this mean it is not possible to support local version identifiers with scikit-build-core or is there some other way to achieve this?

**Comment by LecrisUT** [comment]
On the CMake side, no. You can create another variable to store `VERSION_FULL` and other such metadata.

Shameless plug though, you can try my [`DynamicVersion`](https://github.com/LecrisUT/CMakeExtraUtils/blob/5d8159edda492919deb759051f080d765f3df4b4/cmake/DynamicVersion.cmake) CMake module and have both CMake and scikit-build-core get the full version from vs

**Comment by jonyscathe** [comment]
Hey,
Thanks for your help.

Didn't have much luck with setting VERSION_FULL, not too sure where to set that?

With DynamicVersion, the suffix part of the tag still doesn't come through. And I get a warning:
`/tmp/build-env-yun_p5r7/lib/python3.12/site-packages/setuptools_scm/version.py:102: UserWarning: tag 'v12.4.0+local0' will be stripped of its suffix '+local0'`

`.dev0+g64b4748` style suffixes come through fine with DynamicVersion so it seems like it should all be possible, but no luck with the +local0 suffix 

Also, the installation instructions on CMakeExtraUtils could probably be improved.
The second example should probably include `include(FetchContent)`, spell `FetchContet_Declare` correctly and spell `LecriUT` correctly.

**Comment by LecrisUT** [comment]
> Also, the installation instructions on CMakeExtraUtils could probably be improved.

Thanks for that catch

> .dev0+g64b4748 style suffixes come through fine with DynamicVersion so it seems like it should all be possible, but no luck with the +local0 suffix

Yes, what I meant with `DynamicVersion` is to use dev or post style version format (see setuptools-scm [documentation](https://setuptools-scm.readthedocs.io/en/latest/extending/#available-implementations)). `local` format is not meant to be under vcs by definition.

Can you elaborate on how/where you use that format?

> Didn't have much luck with setting VERSION_FULL, not too sure where to set that?

There I meant just to define and use such variable manually instead of passing to `project`. You can use a regex to strip the suffix part to use in `project` and use the full part somewhere else, e.g. in a `version.h.in` file.

**Comment by henryiii** [comment]
We should not be including anything beyond what CMake supports in `SKBUILD_PROJECT_VERSION`, including the suffix was an oversize. I wonder if we should have a `SKBUILD_PROJECT_VERISON_FULL` or similar to access it if needed, though?

**Comment by LecrisUT** [comment]
> I wonder if we should have a `SKBUILD_PROJECT_VERISON_FULL` or similar to access it if needed, though?

Would definitely need a full version somehow for tests that check C/C++ version vs python version. But on the other-hand, these variables imply building the main C/C++ project is dependent on skbuild-core, so the C/C++ interface is not expected to be exported individually, except for conda probably. The use-case of `SKBUILD_PROJECT_VERSION` is rather limited imo.
