### ISSUE TITLE
Wheel build tag support

### ISSUE THREAD

**Issue by mryzhov** [scikit-build/scikit-build-core#611]
Hello, 

According to the https://peps.python.org/pep-0491/ the wheel name may include {build tag}, which is useful when the wheel packaging is part of CI, do you have a plans to support it?

The wheel filename is {distribution}-{version}(**-{build tag}**)?-{python tag}-{abi tag}-{platform tag}.whl.

Thanks, 
Mikhail

**Comment by henryiii** [comment]
That's a deferred PEP, and the original doesn't include details about build-tag, and the official specs don't include details either (just the one mention in the wheel name string), so I'm basing it generally on a restrictive form of the deferred PEP: Must start with a number, and contain only letters, numbers, and `_`.

**Comment by henryiii** [comment]
Here's the spec: https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-name-convention
