### ISSUE TITLE
Feed setuptools_scm version information into CMake

### ISSUE THREAD

**Issue by dokempf** [scikit-build/scikit-build-core#631]
I am wondering whether it would be somehow possible to pass the versioning information that `setuptools_scm` extracts from the Git repository to the CMake build triggered by `scikit-build-core`. My use case is that my compiled sources do not only build a shared library, but also a command line utility. This CLI utitility should also be able to report the correct version information it was built with. Any input for this would be appreciated!

**Comment by LecrisUT** [comment]
Depends on if you want the project to be built only within `scikit-build-core` or also a standalone. For the former you have `SKBUILD_PROJECT_VERSION` and `SKBUILD_PROJECT_VERSION_FULL`. For the latter case you can use my [`DynamicVersion`](https://github.com/LecrisUT/CMakeExtraUtils/blob/main/cmake/DynamicVersion.cmake) module which basically replicates the logic of `setuptools_scm` as closely as possible.

**Comment by dokempf** [comment]
Thanks for the fast answer - I was not aware of these variables. I would also love to support standalone builds, but unfortunately, I cannot use GPL code for this particular project. The effort of providing DynamicVersion is still appreciated.

**Comment by LecrisUT** [comment]
I can relicense it if you can advice on what the difference between the licenses are. I think consuming via `FetchContent` or `find_package` would no break any license issues?
