### ISSUE TITLE
[feature] tool.scikit-build.cmake.define cannot parse cmake variable

### ISSUE THREAD

**Issue by Freed-Wu** [scikit-build/scikit-build-core#633]
## Reproduce steps

```toml
[tool.scikit-build.cmake.define]
NULL = "${SKBUILD_NULL_DIR}"
```

```cmake
message("${NULL}")
```

However:

## Actual behaviour

```sh
$ pyproject-build -w
...
${SKBUILD_NULL_DIR}
```

## Expected behaviour

```sh
$ pyproject-build -w
...
/tmp/tmp68vlvjk7/build/null
```

**Comment by LecrisUT** [comment]
That is tricky because where do you get the cache/non-cache variable to expand those? Some variables are also defined later on from `FetchContent`.

These type of extensions are better done within cmake using `if(DEFINED) `

**Comment by Freed-Wu** [comment]
> These type of extensions are better done within cmake using `if(DEFINED)`

Can we get them from `pyproject.toml`?

**Comment by LecrisUT** [comment]
Maybe only the default ones, but then:
- there could be confusion upon which variable is expanded or not
- we would have to support recursive out-of-order expansions
- there are other macros like `$ENV{}`
- handling whitespace and escape characters will be tricky

If you want to have some fun, try setting a variable to `]==]") message(FATAL_ERROR ...`

I'm particularly wary about in your example about the promotion of a non-namespaced local variable to a cached one, which can then affect other projects.
