### ISSUE TITLE
Specifying `editable.mode=inplace` when `build-dir` already set in `pyproject.toml` is not supported

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build-core#642]
This issue is related to the `inplace` experimental mode associated with editable install.

Links:
* https://scikit-build-core.readthedocs.io/en/latest/configuration.html#editable-installs
* https://github.com/scikit-build/scikit-build-core/pull/553

**Comment by henryiii** [comment]
Ahh, okay. You can set the build-dir to “” until this is fixed.
