### ISSUE TITLE
Inconsistent `install.strip` documentation

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build-core#680]
The README currently states:

```
# Whether to strip the binaries. True for scikit-build-core 0.5+.
install.strip = false
```

However, scikit-build-core is > 0.5: my expectation is to see `install.strip = true` here.

**Comment by henryiii** [comment]
We should probably override this. It's actually set to None, IIRC, and that gets rendered in the README as False.

**Comment by thewtex** [comment]
Closed via https://github.com/scikit-build/scikit-build-core/pull/681
