### ISSUE TITLE
`zipfile.BadZipFile: Bad magic number for file header`

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#696]
This is about an [issue](https://github.com/spglib/spglib/issues/468) on the release of `spglib`. Basically it concerns the artifact of `scitkit-build-core` + `cibuildwheel`: https://github.com/spglib/spglib/actions/runs/8647336672/job/23714377810

Weird thing is `dist/spglib-2.4.0-cp310-cp310-macosx_10_9_x86_64.whl` works well, but `dist/spglib-2.4.0-cp311-cp311-macosx_10_9_x86_64.whl` fails with the issue in the title.

**Comment by henryiii** [comment]
This is https://github.com/actions/download-artifact/issues/298

You must have unique names in the artifacts. Make sure you are not producing the same wheel twice.

**Comment by LecrisUT** [comment]
Oh indeed I had 2 runner `macos-13` and `macos-11`. Did not expect them to just merge the files together. Why is that not producing errors?

**Comment by henryiii** [comment]
There's a bug in that action where instead of producing an error (which is what I'd prefer) or picking the first or last matching file, `download-artifact` just garbles the bits. This most notably shows up on file formats that have some error checking (like zip).
