### ISSUE TITLE
`version` dynamic fields?

### ISSUE THREAD

**Issue by hobu** [scikit-build/scikit-build-core#710]
sckit-build-core is really shaping up! I recently refactored the [PDAL Python bindings](https://github.com/PDAL/python/pull/165) to use it, and I am quite pleased with how it simplified and modernized things.

The only significant sticking point is `version`. As it is now, my config must either have it defined in two places (both the CMakeLists.txt and the Python) or define it in CMakeLists.txt and use a custom command to write it out into the Python. Neither of these options are very pleasant.

I know full dynamic fields isn't an option at the moment. Is there a roadmap or timeline for them, and if not, could a special case be made for this very common `version` need?

**Comment by LecrisUT** [comment]
What's the issue with the regex parser? https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata. Just need to make it recognize `project(VERSION)`.

I also got a [CMake module](https://github.com/LecrisUT/CMakeExtraUtils/blob/main/cmake/DynamicVersion.cmake) that you can use to make both CMake and python recognize `setuptools-scm` logic. Note though `.git_archival.txt` should remove `ref-names`.

**Comment by henryiii** [comment]
You can also generate a file for Python if you want it in the wheel, SDist, or source tree with `[[tool.scikit-build.generate]]`.

**Comment by LecrisUT** [comment]
That is generated by `scikit-build-core` right? I guess the main question there is if the project is intended to be buildable only through `pip install` (or any PEP517) or if it is meant to be built as standalone as well. In each case the dynamic version can be supported with the current implementations.

**Comment by henryiii** [comment]
That’s generated, yes. You combine it with dynamic metadata. So you can pull tge version from CMake then add a _version.py or similar in the wheel (or SDist or in place). Saves having to pull the version dynamically. Setuptools_scm can do this but it must be in place. This works with any metadata source (it takes a template).

**Comment by hobu** [comment]
The following worked perfectly for me with 0.9.0. Thanks!

```
[project]
dynamic = ["version"]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "src/project/__init__.py"
```
