### ISSUE TITLE
Pyodide support

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#715]
#675 switched to using `cmake -E capabilities`. But Pyodide injects `--fresh` to all cmake commands, so this broke pyodide support. Until https://github.com/pyodide/pyodide/issues/4704 is resolved and released, we should fall back to `--version` if this fails to fix pyodide.

**Comment by LecrisUT** [comment]
A quick recap on how the 2 projects are related? Injecting `--fresh` sound like it would break any `cmake` command, including `cmake --build`, how is that not broken before?

Oh they actually have specific checks for those :/
```python
        # If it is a build/install command, or running a script, we don't do anything.
        if "--build" in line or "--install" in line or "-P" in line:
```

Looks like there are many other functionalities to include there than: https://cmake.org/cmake/help/latest/manual/cmake.1.html
