### ISSUE TITLE
Please add a possibility to configure builder (`cmake --build`) arguments

### ISSUE THREAD

**Issue by mgorny** [scikit-build/scikit-build-core#722]
FWICS there is currently no way to pass additional arguments to the builder, i.e. the equivalent of:

    cmake --build . -- -j12 -l13

Could you please add a configuration knob for that? We really want to respect user job count and load average options in Gentoo.

**Comment by mgorny** [comment]
Our logic for CMake is pretty complex, as CMake is pretty bad and requires a lot of hacks to work correctly. I'm still considering how to best integrate it with the Python logic: https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/cmake.eclass

Python logic is also quite complex, and we generally try to respect the idea that PEP517 build invocation should do it all: https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/distutils-r1.eclass

For consistency, the best approach for us would be to pass them via `config_settings` dict. We already pass CMake arguments there, and it would be consistent with how we handle `meson-python`.

**Comment by LecrisUT** [comment]
What about on the consumer side, any example packages for each of those? At first glance, Gentoo seems to have quite complex setting for the configure options like `gentoo_rules.cmake`, `gentoo_toolchain.cmake`. But on the build and test side, it looks fairly vanilla and it's more up to the recipe what flags it wants to implement.

**Comment by mgorny** [comment]
Build and test arguments are generally provided by the user in package manager configuration.

For CMake, sometimes additional arguments are passed straight to the function performing the build, e.g.:
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-text/doxygen/doxygen-1.10.0-r1.ebuild#n145
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-mobilephone/gammu/gammu-1.42.0-r1.ebuild#n63

For Python, we currently only override `MAKEOPTS` (this is the variable set by user), to force serial build:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/psutil/psutil-5.9.8.ebuild#n43

**Comment by henryiii** [comment]
This seems reasonable; what would you expect for the name? `build.args` seems like it might refer to `cmake --build . <here>` rather than `cmake --build . -- <here>`? The former isn't an open-ended list (https://cmake.org/cmake/help/v3.29/manual/cmake.1.html#build-a-project), so I'm not sure we need to expose it, but if we ever did, `build.args` would be the best name for that. Maybe `build.tool-args`?

**Comment by mgorny** [comment]
Either way works for me. If it were the former, I'd just pass `--` first :-).

**Comment by mgorny** [comment]
On a second thought, `build.tool-args` would probably be more intuitive.
