### ISSUE TITLE
Nested .gitignore files are ignored when building sdist

### ISSUE THREAD

**Issue by bindreams** [scikit-build/scikit-build-core#726]
Nested `.gitignore` files, i.e. the ones not at the root of the project, are ignored when building sdist.

With a project structure:
```
dir1
  ├ file3
  ├ file4
  └ .gitignore  # file3
file1
file2
.gitignore  # file1
pyproject.toml
```
When building a sdist using `python -m build --sdist`, the top-level `.gitignore` is respected and `file1` is not included. But the nested `.gitignore` inside the directory is ignored completely and both files in that dir are included.

For convenience I created a sample repo that reproduces the issue: https://github.com/bindreams/scikit-gitignore-issue

**Comment by henryiii** [comment]
You didn't need to make a repo, I know that's the way it works currently. :) What I think would make sense would be to either make the default `**/.gitignore`, or `.gitignore` and make `/.gitignore` mean the top one only (that's probably easier), then recurse the tree. I'd be happy to review a PR, and I'll try to get to it in the near future otherwise.

**Comment by slarew** [comment]
In addition to .gitignore files sprinkled around a directory structure, there are other ignores also: https://git-scm.com/docs/gitignore

In particular, I frequently use `$GIT_DIR/info/exclude` to ignore local modifications when it does not make sense to add those ignores to checked-in .gitignore files.

Would it make sense to first try to use git itself to find out what files are under version control? And only if git is unavailable then fall back to walking directories and parsing gitignore files?

**Comment by henryiii** [comment]
That would make the build process dependent on the existence of git, and would cause different results if you have git vs. not. I'd instead use a tool (like https://github.com/henryiii/check-sdist) to compare git's ignores with the `.gitignore` that scikit-build-core (or hatchling, for that matter) are using if you want to compare them.

> I frequently use $GIT_DIR/info/exclude to ignore local modifications when it does not make sense to add those ignores to checked-in .gitignore files.

I don't see why you'd want these local-only excludes to cause files to disappear from your SDists and wheels?

**Comment by slarew** [comment]
Yeah, I agree the potential difference in behavior depending on the existence of git is not great.

**Comment by slarew** [comment]
> > I frequently use $GIT_DIR/info/exclude to ignore local modifications when it does not make sense to add those ignores to checked-in .gitignore files.
> 
> I don't see why you'd want these local-only excludes to cause files to disappear from your SDists and wheels?

If I make a fresh clone of a git repo and then create an sdist from it, that sdist wouldn't contain my locally excluded files because it's a fresh clone.

So why would I want my local files that I intentionally locally excluded from git to be included in the sdist? I don't.

**Comment by slarew** [comment]
I'll add that it's possible (albeit a bit rare I'd imagine) to add files to git that would normally be ignored by gitignore files. I would argue that the expected behavior would be that those files are included in the sdist despite the gitignore rules suggesting they shouldn't be.
