### ISSUE TITLE
Renames now that we have a build section

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build-core#747]
I'd like to rename:

* `cmake.targets` -> `build.targets`
* `cmake.verbose` -> `build.verbose`

Old will work but be deprecated (minimum-version based).

**Comment by LecrisUT** [comment]
`cmake.verbose` would be useful to separate verbose for configure and build stage

**Comment by henryiii** [comment]
Probably also a configure section too, see #790.

**Comment by henryiii** [comment]
I'm not sure what would go in `config`, though. `cmake.args` mirrors `CMAKE_ARGS` better, and we think of it as args to cmake more than configure-time arguments. `configure.preset` sounds good, though.

**Comment by LecrisUT** [comment]
Why not have `cmake.args` be alias to `config.args`? From CMake point of view it kinda mirrors the `cmake` without any option is implicitly configure. Would fit more naturally with `build.args`.

But also `tool.scikit-build.config.xxx` or `tool.scikit-build.cmake.config.xxx`? I don't think the latter is too verbose when it is being used within a group `tool.scikit-build.cmake`

**Comment by henryiii** [comment]
I don't like the idea of a permeant alias. Then you have to solve the question of what to do if both are specified. Though I do like the potential symmetry there somewhat, but these are cmake args as well, while build args are not cmake args.
