### ISSUE TITLE
Trigger warning if `build-system.requires` contains cmake or ninja

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#780]
Since explicitly adding `cmake` and `ninja` to the `build-system.requires` can cause so much trouble, how about parsing the field and trigger a deprecation warning to move that to `tool.scikit-build`, and eventually block the build if it's still defined there?

**Comment by henryiii** [comment]
We can add the warning when we add #777 for the scikit-build-core min version. I don't think we should block, but a warning is probably fine.
