### ISSUE TITLE
Generated json schema does not render roles properly

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#794]
It's about the [full-schema](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#full-schema)

For example: `metadata.version`

**Comment by henryiii** [comment]
Ah, you mean `=3.15` instead of `>=3.15`?

**Comment by LecrisUT** [comment]
No, I  mean it renders as `:ref:#/$defs/metadata` instead of expanding it
![image](https://github.com/scikit-build/scikit-build-core/assets/25577083/7168fdbd-a820-4f2d-a9dc-e5dad885ee16)

**Comment by LecrisUT** [comment]
Is it just me on mobile or are the links not clickable there? Ref part is gone at least, but it's still confusing if it's only that name

**Comment by henryiii** [comment]
I've played a bit with the options at https://sphinx-jsonschema.readthedocs.io/en/latest/directive.html#options but didn't get clickable links with any combination I tried.

**Comment by LecrisUT** [comment]
Seems like an upstream bug. But what about separating the json schema tables (similar to how you do for the python API). There's a small `Benefits` box next to example [^1] and there the linking seems to work. Maybe it doesn't work because inside the table there is no linkable target?

[^1]: https://sphinx-jsonschema.readthedocs.io/en/latest/schemakeywords.html#caption
