### ISSUE TITLE
Help locating isolated package requirements in temp folder from within CMake

### ISSUE THREAD

**Issue by Pydes-boop** [scikit-build/scikit-build-core#802]
Hi, so what im trying to do is probably fairly odd and i might be fundamentally misusing the build process but im building a cpp library for python using pybind and generating stubs using pybind11-stubgen. 

The issue is that pybind11-stubgen can only generate stubs for a python library if it can import the library on a module level, while i want to already generate these stubs during the build process to package them with the finished wheels.

My Idea here would now be that after i have generated my .so / .pyd file with my CMake i add a POST_BUILD and link the .so / .pyd file to my current python library path for the temp cmake environment and build the .pyi files that way:

```
add_custom_command(
		TARGET ${PROJECT_NAME} POST_BUILD
		# linking the built .so/.pyd file into a temp pythonpath for cmake so pybind11-stubgen can find it
		COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=$<TARGET_FILE_DIR:${PROJECT_NAME}>:$ENV{PYTHONPATH} ${PYTHON_EXECUTABLE} -m pybind11_stubgen example_project
		COMMENT "Generating pybind11 stubs for example_project"
		WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/..
		VERBATIM
)
```

for this to work i require numpy and pybind11-stubgen available on my system, but this availability is a little incosistent even though they are both requirements in my pyproject.toml.

Generally if i do this and create a seperate venv, first install pybind11-stubgen and numpy manually and then build it is able to generate my stubs this way, because python can find the required modules. 

But because this POST_BUILD cmake command executes during the scikit-build process if the required modules are NOT installed before building my python package, they are not yet available to my python interpreter during the build process as the collected packagesare saved into an isolated temp build environment:

```
Installing collected packages: pybind11-stubgen, pybind11, pathspec, packaging, numpy, cmake, scikit-build-core
 C:\Users\NAME\AppData\Local\Temp\pip-build-env-t32janse\overlay\Scripts
Successfully installed cmake-3.30.0 numpy-2.0.0 packaging-24.1 pathspec-0.12.1 pybind11-2.13.1 pybind11-stubgen-2.5.1 scikit-build-core-0.9.8
```

is there any macro or other way with which i can located the temp folder (where the collected packages are located) from within CMake? I would like to access this location and temporarily add it to my python library path so python can already use the collected packages for custom commands during the build process.

Or is there any other way in which i could make any packages that are requirements of the pyproject.toml available for my python environment during the build process already?

In general i think not using an isolated build environment fixes this in some cases, but preferably i would like it if i could still stay within an isolated build env.

**Comment by henryiii** [comment]
> collected packagesare saved into an isolated temp build environment


This should be the environment `Python_EXECUTABLE` (and `PYTHON_EXECUTABLE`, etc) are using. Do you have some (non-working) package code to check?

**Comment by Pydes-boop** [comment]
Thanks you are absolutely correct!

I did some further testing and realized that it was a problem specific to my windows build as i was concatinating the pythonpath wrong for the platform.

The way i have it implemented now so i can execute pybind11-stubgen as a post build on our pybind11 binary is:

```cmake
if (WIN32)
    set(SEP ";")
else ()
    set(SEP ":")
endif ()

add_custom_command(
    TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E env "PYTHONPATH=$<TARGET_FILE_DIR:${PROJECT_NAME}>${SEP}$ENV{PYTHONPATH}" ${PYTHON_EXECUTABLE} -m pybind11_stubgen example_project -o ${CMAKE_CURRENT_SOURCE_DIR}
    COMMENT "Generating pybind11 stubs for example_project"
)
```

where we set the current cmake source directory as the output so the scikit-build-process gets the .pyi file and can copy it into the final wheel (though probably here the tmp folder could also just be used as the output in some way).

**Comment by henryiii** [comment]
FYI, I think you might need "" around the CMAKE_COMMAND, just in case there are spaces in the path, and I think you can do something like this if want (really badly) to avoid the separate definition of SEP:

```cmake
add_custom_command(
    TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND
      "${CMAKE_COMMAND}" -E env
      "PYTHONPATH=$<TARGET_FILE_DIR:${PROJECT_NAME}>$<IF:$<PLATFORM_ID:Windows>,$<SEMICOLON>,:>$ENV{PYTHONPATH}"
      "${Python_EXECUTABLE}" -m pybind11_stubgen
      example_project -o "${CMAKE_CURRENT_SOURCE_DIR}"
    COMMENT "Generating pybind11 stubs for example_project"
)
```

**Comment by Pydes-boop** [comment]
Thanks so much, i added all of these suggestions as well!
