### ISSUE TITLE
CMake and Ninja are not installed by scikit-build-core

### ISSUE THREAD

**Issue by bryanwweber** [scikit-build/scikit-build-core#806]
Hello! I've set the `tool.scikit-build.cmake.version` value to something greater than my system version (Ubuntu 22.04, CMake 3.22.1). The [docs](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#cmake-and-ninja-minimum-versions) say that scikit-build-core will attempte to install CMake (and/or ninja) if the appropriate version is not found, but this hasn't happened for me.

I'm not sure if this is a problem or as designed. If the latter, should the docs be updated to reflect the actual behavior? Thank you!

**Comment by henryiii** [comment]
What command are you using to build? It should be injected by `get_requires_for_build_wheel` during the isolated build process.

**Comment by bryanwweber** [comment]
I'm sorry to make such an awful bug report. As it turns out, I can't even reproduce this behavior any longer, so I'll just close this. Thanks for your quick reply!
