### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by yichuanlu** [scikit-build/scikit-build-core#832]
I recently created a simple package using pybind11, cmake, and scikit-build-core, and uploaded the source distribution to [test.pypi.org/project/tripleit/](https://test.pypi.org/project/tripleit/). However, I encountered a perplexing issue during installation:

1. If I run `pip install -i https://test.pypi.org/simple/ tripleit`, the build system fails with the following error:
> Installing build dependencies ... error
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> [3 lines of output]
>     Looking in indexes: https://test.pypi.org/simple/
>     ERROR: Could not find a version that satisfies the requirement scikit-build-core>=0.3.3 (from versions: none)
>     ERROR: No matching distribution found for scikit-build-core>=0.3.3
>     [end of output]

2. Interestingly, if I manually download the source distribution from [test.pypi.org/project/tripleit/](https://test.pypi.org/project/tripleit/) and then run `pip install .`, the package installs correctly without any issues. 

Any thoughts on how to fix this problem? Thank you in advance!

P.S. Here is my pyproject.toml file:

> [build-system]
> requires = ["scikit-build-core>=0.3.3", "pybind11"]
> build-backend = "scikit_build_core.build"
> 
> [project]
> name = "tripleit"
> version = "1.0.5"
> requires-python = ">=3.7"

**Comment by henryiii** [comment]
You are forcing pip to _only_ look at Test PyPI - scikit-build-core (and pybind11) are not on Test PyPI. You need to allow normal PyPI too if you want to install scikit-build-core (also pybind11). You can do this by replacing `-i/--index-url` with `--extra-index-url`. Alternatively, you can pre-install the build requirements (scikit-build-core and pybind11) and then use `--no-build-isolation` to build using the current environment with the pre-installed dependencies.

**Comment by yichuanlu** [comment]
Thank you for the clear and prompt reply—it works!

Given this, would it be risky to use `pip install [mypackage] -i https://test.pypi.org/simple/` as suggested by Test PyPI? If someone uploads a fake version of pybind11 or scikit-build-core to Test PyPI, pip would use that as the dependency.

On the other hand, if testers use `pip install [mypackage] --extra-index-url https://test.pypi.org/simple/`, and if there is a package with the same name as `[mypackage]` on the normal PyPI, then I assume the one on the normal PyPI repository would be installed?

**Comment by LecrisUT** [comment]
Please do not instruct users to use `test.pypi` to install your package. That is only meant to test if you are able to upload to PyPI properly. Either pubslih to PyPI with beta matadata, release candidate etc., or tell users to install using `pip install https://github.com/...` (or equivalents, see pip documentation)

**Comment by henryiii** [comment]
I didn’t remember the order, but the inverse is `pip install [mypackage] -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/`.

Though @LecrisUT is right, TestPyPI is only for checking if you can upload a package. They may delete up to everything on it at any time. Any package you find there is not even likely to work.

If you need an alternative index, there are others, anaconda has one I believe.

**Comment by yichuanlu** [comment]
I agree; I would never advise any user to install my package from TestPyPI. However, after uploading packages to TestPyPI, it’s tempting to test if I can download and install them, especially since the official Python packaging guide includes this step: [Using TestPyPI](https://packaging.python.org/en/latest/guides/using-testpypi/).

The official guide also recommends using `pip install [mypackage] -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/`. Following the discussion above, this command will prioritize TestPyPI: if pip cannot find `[mypackage]` or its dependencies there, it will then search in the normal PyPI repository. This approach still seems somewhat risky. For instance, I noticed a “fake” scipy on TestPyPI. If my package depends on the real SciPy, the command above could result in pip installing my package with the fake scipy.
