### ISSUE TITLE
single sourcing the version string

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [scikit-build/scikit-build-core#839]
right now, we have a version string in our code:

__version__ = x.x.x

and have to hard-code it in the pyproject.toml as well, which , of course is NOT a good practice.

There's a lot of discussion around this, but everyone agrees that it shoudl be single sourced.

So how to do it with scikit-build?

It *looks* like I may be able to use hatchling to do that (and other stuff), but It's also not at all clear to me what is supported by hatchling, or how to use it.

Anyone have an example anywhere?

**Comment by ChrisBarker-NOAA** [comment]
A follow-on note -- I tired using hatchling -- and in fact, quite amazingly, it "jsut worked" -- whoo hoo!

However, then I got:
```
 File "/private/var/folders/7t/137hx7xn4s1fdqvjj1bhtdhrz84cy3/T/pip-build-env-tvqu3pdl/overlay/lib/python3.10/site-packages/scikit_build_core/hatch/plugin.py", line 121, in initialize
          raise ValueError(msg)
      ValueError: Editable installs are not yet supported
```
Darn -- so, IIUC, scikit-build can do editable, and hatch can do editable, but not together :-(

editable installs are a critical feature of my workflow, I have non idea how else I could possibly work without it -- so I guess I'm back to plain scikit build and none of the nifty stuff hatch provides -- oh well.

**Comment by henryiii** [comment]
> So how to do it with scikit-build?

See https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata - click the "regex" tab. You can pull string metadata out of a file, and the default is even good for the normal Python way of doing it.

(You can also put the single-source version in pyproject.toml, then use the generate feature to write it out to a file, that's the following section in the docs)

> scikit-build can do editable, and hatch can do editable, but not together

Yes, Hatching's editable install is much simpler, and can't support the dual directory design we use, so we'll have to do a lot of coordination to make that happen. The "inline" mode is probably much easier to support, though, so might work on that in the future.

**Comment by ChrisBarker-NOAA** [comment]
Ahh --- thanks! I saw the setuptools_scm way, but it doesn't work for me -- didn't think to click on the regex tab -- trying it now.

**Comment by ChrisBarker-NOAA** [comment]
And it works -- thanks!
