### ISSUE TITLE
sdist.exclude should not be overridden by .gitignore

### ISSUE THREAD

**Issue by alexreinking** [scikit-build/scikit-build-core#871]
My `.gitignore` file uses the following trick to ignore (most) files without extensions:

```
*
!*.*
!*/
```

Unfortunately, the way that `sdist.exclude` is implemented is by _prepending_ the listed rules to these. These are then overridden by the `*` in the file.

I believe that `sdist.exclude` should be implemented similarly to `sdist.include`; in a separate `pathspec` that is checked after `sdist.include` and which gets final say.

**Comment by henryiii** [comment]
Slightly related: https://github.com/scikit-build/scikit-build-core/issues/858

**Comment by henryiii** [comment]
I think that makes sense. Would you like to attempt it?
