### ISSUE TITLE
Can not correctly assign the file path from `target_compile_definitions` in CMakeList.txt

### ISSUE THREAD

**Issue by Haoran-Zhao** [scikit-build/scikit-build-core#913]
@henryiii @LecrisUT Thanks so much for the help in last closed [issue](https://github.com/scikit-build/scikit-build-core/issues/911). I have followed your guidance but the second problem is still remained. I would like to pose more detail here, I'm not sure if this is the scikit issue or some function is not supported.

In my project CMakeList.txt
```
    if(DEFINED SKBUILD_PLATLIB_DIR)
      message(STATUS "SKBUILD_PLATLIB_DIR: ${SKBUILD_PLATLIB_DIR}")
      set(INSTALL_DIR ${SKBUILD_PLATLIB_DIR}/${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/urdf)
    else()
      set(INSTALL_DIR ${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/urdf)
    endif()

    target_compile_definitions(my_package_py
      PRIVATE
        INSTALLED_URDF_PATH="${INSTALL_DIR}"
    )

    install(DIRECTORY ${CMAKE_SOURCE_DIR}/urdf/
      DESTINATION ${INSTALL_DIR}
      FILES_MATCHING PATTERN "*.urdf"
    )

```

In .toml
```
# config or envvar will override toml. See also ``cmake.define``.
cmake.args = ["-DBUILD_PYTHON_BINDINGS=ON", "-DBUILD_TESTING=OFF"]

# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"

# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"

# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

# The build type to use when building the project. Valid options are: "Debug",
# "Release", "RelWithDebInfo", "MinSizeRel", "", etc.
cmake.build-type = "Release"

# Verbose printout when building.
cmake.verbose = true

# If set to True (the default), CMake will be run before building the wheel.
wheel.cmake = true
```

The verbose logs from `pip wheel`
```
*** Building project with Ninja...
.....
[8/27] /usr/bin/x86_64-linux-gnu-g++ -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 

-DHPP_FCL_HAS_OCTOMAP -DHPP_FCL_HAVE_OCTOMAP -DINSTALLED_URDF_PATH=\"/tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf\" -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=7 

-DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -DURDF_PATH=\"/workspaces/src/my_package/urdf/\" -I/workspaces/src/my_package/include -isystem /usr/local/include/eigen3 -isystem /opt/ros/humble/include/urdfdom -isystem /opt/ros/humble/include/urdfdom_headers -O3 

-DNDEBUG -fPIC -std=c++20 -MD -MT CMakeFiles/my_package.dir/src/ik_solver.cpp.o -MF CMakeFiles/my_package.dir/src/ik_solver.cpp.o.d -o CMakeFiles/my_package.dir/src/ik_solver.cpp.o -c /workspaces/src/ik_solver.cpp
.....
*** Installing project into wheel...
  -- Install configuration: "Release"
  ......
  -- Installing: /tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf/panda.urdf
  ......
 -- Installing: /tmp/tmpnc87syyx/wheel/platlib/lib/python3.10/site-packages/my_package/my_package_py.cpython-310-x86_64-linux-gnu.so
  -- Set runtime path of "/tmp/tmpnc87syyx/wheel/platlib/lib/python3.10/site-packages/my_package/my_package_py.cpython-310-x86_64-linux-gnu.so" to ""
 .......
 -- Up-to-date: /tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf/panda.urdf
```
As above shown, the `INSTALLED_URDF_PATH=\"/tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf\`

After the wheel is successfully built and installed, I tried to run my code, and my code use the compilation defination as 
```
    std::string urdf_path = std::filesystem::path(INSTALLED_URDF_PATH) / "panda.urdf";
```
and got the following error
```
Error:   File /tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf/panda.urdf does not exist
         at line 55 in ./urdf_parser/src/model.cpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The file /tmp/tmpnc87syyx/wheel/platlib/share/my_package/urdf/panda.urdf does not contain a valid URDF model.
```

Is there a way to work around this or it's not a supported feature? Thanks!

**Comment by LecrisUT** [comment]
This is the issue of not being relocatable. The best approach would be to construct the relative path between the bindir and the `CMAKE_INSTALL_DATAROOTDIR`. Although you might also be able to just remove `SKBUILD_PLATLIB_DIR` and install everything under the package path with the same `CMAKE_INSTALL_DATAROOTDIR` folder structure

**Comment by Haoran-Zhao** [comment]
@LecrisUT not sure how to do the relative path, tried some stuff and did not make it work. I also tried second option to remove `SKBUILD_PLATLIB_DIR` use same  `CMAKE_INSTALL_DATAROOTDIR` 
it throws following error, at lease this time  it doesnt start with `tmp`
```
Error:   File share/my_package/urdf/panda.urdf does not exist
         at line 55 in ./urdf_parser/src/model.cpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The file share/my_package/urdf/panda.urdf does not contain a valid URDF model.
```

**Comment by henryiii** [comment]
Each of the wheel folders cannot refer to the others. You can't reliably compute a relative path between them. `SKBUILD_PLATLIB_DIR` can't know exactly where it will be installed relative to `SKBUILD_DATA_DIR`, same with `SKBUILD_SCRIPTS_DIR`, etc. (Technically, I think you could construct `SKBUILD_METADATA_DIR` vs `SKBUILD_PLATLIB_DIR`, but that's the only one, and it's not the same as it's laid out in the wheel as on disk, at least the names are different).

I think you are installing everything into site-packages? That's what you want to do. Then you'd get the path from Python, and pass it into C++. Python will be able to produce the correct path (either relative to the current file, or via importlib.resources, whichever way you want to go).

**Comment by Haoran-Zhao** [comment]
@henryiii Got it, in this case, I will change the interface to take the path as input. For my case, it might be hard to get the python path which depends on the python version. Thanks again for the help from both of you. I would like to close the issue.

**Comment by henryiii** [comment]
If you’re running from Python as an extension module, that should be easy. If you’re not running it from Python, then it depends on if you’ve wrapped it in an entry point or are installing it directly to scripts. I believe you cannot reliably create the correct path from scripts, so you have to either also install your data files into scripts, or you have to use one of the other methods. This is why the cmake package has a wrapper entry point.
