### ISSUE TITLE
Unable to find pre-built third-party library during build because build is not relative to project root

### ISSUE THREAD

**Issue by mhentz** [scikit-build/scikit-build-core#929]
Hey, I'm trying migrate a working CMake build to scikit-build-core. I want to include pre-built libraries but have so far been unsuccessful in doing so. I will focus on only one of the libraries I want to include to simplify things, it's Blosc2.

My directory structure looks something like this
```
- src/
  - python/
     - __init__.py
  - cpp_extension/
    - CMakeLists.txt
    - main.cpp
    - third_party/
      - blosc2/
- CMakeLists.py
- pyproject.toml
```

And my pyproject.toml contains the following
```
[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "my-package"
version = "0.0.1"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
```

In `./CMakeLists.txt` I add the directory `src/cpp_extension`
```
add_subdirectory(src/cpp_extension)
```

and in `src/cpp_extension/CMakeLists.txt` I set the paths for Blosc with
```
set(Blosc_DIR third_party/blosc2/lib/cmake/Blosc2)
set(BLOSC_LIBRARIES ${CMAKE_CURRENT_SOURCE_DIR}/third_party/blosc2/lib/libblosc2.a)
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${Blosc_DIR})
find_package(Blosc2 REQUIRED)
```

Now, even though I set `build-dir = "build/{wheel_tag}"` in pyproject.toml, the build occurs in a temporary directory and it is unable  to find `third_party/blosc2/lib/cmake/Blosc2/Blosc2Config.cmake` (relative to `src/cpp_extension/CMakeLists`) and the configuration fails. If I hard-code the absolute path to `third_party/blosc2/lib/cmake/Blosc2` the configuration passes, but I don't see why the relative path, which works with CMake, doesn't work here anymore.

Could I please have some pointers on how to resolve this? I'm wondering if I should compile Blosc2 at build-time as I assume it'll be properly included then. How would I handle a header-only library that doesn't need compiling and will presumably cause the same issue?

I'm using CMake version 3.30.5.

Please let me know if any clarification is needed. Thanks for your help!

**Comment by LecrisUT** [comment]
What is the folder structure of `third_party/blosc2`? `find_package` is meant tobe used to find a package that is *installed* on the system, not for a dependency that is bundled (usually handled via `add_subdirectory` or `FetchContent`).

Also worth asking, are you planning to distribute such a project or just build for your own environment?

**Comment by henryiii** [comment]
> the build occurs in a temporary directory

It shouldn't be. Site-packages is still a temporary directory (that's controlled by pip/build/uv, etc), but the build directory is where you request it to be. If it's not, that could be a bug, but this should work. Did you check to see if a `build/*` dir was created?

Usually you use FetchContent and/or add_subdirectory. Ideally you should use CMake 3.25+'s support for combining find_package and download-if-missing features.

**Comment by mhentz** [comment]
Thank you both for the swift responses! I hadn't come across `FetchContent` before so I will have a look at that.

> What is the folder structure of third_party/blosc2?

It's the directory I install the library to after I've compiled it. Looks something like this:
```
- third_party/blosc2/
  - include/ (contains the usual suspects)
  - lib/
    - cmake/
      - Blosc2/
        - Modules/
          - Find*.cmake (cmake files for libraries included in blosc2)
        - Blosc2Config.cmake
        - ... (some more cmake files)
    - pkgconfig/
      - blosc2.pc
    - libblosc2.* (dynamic and static library builds)
```


>  are you planning to distribute such a project or just build for your own environment?

I'm initially building my own environment but will want to distribute it eventually. I have previously done this by shipping manylinux wheels built in a Docker container. I would prefer for my users to be able to build the package themselves in case I don't provide a wheel for their architecture but I hadn't got that far yet.


> Did you check to see if a build/* dir was created?

I did check and couldn't find one. I will try again in a clean environment later this evening and see if that makes a difference.

**Comment by LecrisUT** [comment]
My recommendation is to start small, get it running in your own environment and then work your way up. But you have to understand what are the typical workflow a user would use, since we want to encourage good CMake and packaging practices.

- Do not install in `third_party/*` because we do not expect those paths to contain binary artifacts:
  - Instead install to your local environment, usually `$HOME/.local`, but you can put it in whatever folder structure you want (beware if you need RPATH and LD_LIBRARY_PATH when you install blosc2 dependency)
  - Common design is that `third_party/*` contains the (vendored) source files of `blosc2` and you consume it with `add_subdirectory` (effectively rebuilding blosc2 as part of your project)
  - `FetchContent` is a preferred modern design instead of `third_party/*` vendoring, but there are legitimate designs to use both.
- After you install the dependency, you would want to add the path manually via `CMAKE_PREFIX_PATH` environment/cmake variable

There are various other questions you need to ask yourself when considering how you want to package your project, but you should first get comfortable with CMake workflows, and at the very least understand the differences between `add_subdirectory`, `find_package` (and `FetchContent`).

**Comment by mhentz** [comment]
Thanks again for your input. I'm currently looking into the proposed solutions and trying them out.

@henryiii I had another go at setting `build-dir = "build/{wheel_tag}"` in pyproject.toml. This time I used the [pybind11 example linked in the docs](https://github.com/pybind/scikit_build_example) and only made one change to add the build directory to the `[tool.scikit-build]` table. I was previously using uv as the installer which didn't create a `build` directory nor did it install the package successfully but after I switched to installing using pip directly it worked fine and I can now see the `build` directory.

**Comment by mhentz** [comment]
After a rather long evening I've been successful in building my extension. I decided to include the third-party libraries in the build as you suggested using `FetchContent`. I had been going at it for a few days trying to coax the correct answers out of ChatGPT–incredible amounts of rubbish. Can't beat highly knowledgeable software developers!

Thank you both for your invaluable help  :)
