### ISSUE TITLE
Meeting url outated?

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#930]
Seems like the google meet room has changed?
https://github.com/scikit-build/scikit-build-core/blob/f461bb139589871a0c8f2cba823f9d8965066824/README.md?plain=1#L18

**Comment by henryiii** [comment]
I believe it got canceled an hour or so before the meeting today and that causes the Google meet link to report that. (Why it was canceled, I'm not sure, I was ready for one.)

**Comment by henryiii** [comment]
Ahh, I wonder if it's because @thewtex left Kitware and he was the owner of the meeting?

**Comment by LecrisUT** [comment]
Hmm, probably also good to have a link for the google calendar event of the meeting, or something to track the status

**Comment by henryiii** [comment]
We should set up a room, I think. I created on at https://meet.google.com/kmh-snuy-dhv that we could use.

**Comment by henryiii** [comment]
I'll join that one for a bit if you'd like to briefly meet (@jcfr if you are around, too)

If the room doesn't go away after we use it, we could make it the standard room.

**Comment by henryiii** [comment]
Stuck trying to authenticate, be back in a bit.

**Comment by jcfr** [comment]
Unclear is Google Meet updated their ID or not ... in the meantime, the correct reference has been set in https://github.com/scikit-build/scikit-build-core/pull/931

See also https://meet.google.com/qbx-nkkm-mup
