### ISSUE TITLE
Vcpkg cant find dumpbin on windows

### ISSUE THREAD

**Issue by TeSheng93** [scikit-build/scikit-build-core#936]
For a cmake vcpkg project, when `X_VCPKG_APPLOCAL_DEPS_INSTALL`  is set to `ON` vcpkg will find all required DLLs and copy them to the INSTALL directory upon build. Internally it calls [dumpbin](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L96) to determine what's needed.

When building with scikit build core, it seems that vcpkg could not find `dumpbin` and I get the following error:
```ps
-- Installing app dependencies for lib_1...
resolve: D:\github\scikit_build_core_vcpkg_dumpbin\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:162:1
Line |
 162 |  resolve($targetBinary)
     |  ~~~~~~~~~~~~~~~~~~~~~~
     | Neither dumpbin, llvm-objdump nor objdump could be found. Can not take care of dll dependencies.
*** Making wheel...
*** Created dumpbin_not_found-0.0.0-cp312-cp312-win_amd64.whl
```

Removing the `-ErrorAction SilentlyContinue` from [L96](https://github.com/microsoft/vcpkg/blob/master/scripts/buildsystems/msbuild/applocal.ps1#L96) shows:
```ps
Get-Command: D:\github\scikit_build_core_vcpkg_dumpbin\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:96:9
Line |
  96 |      if (Get-Command "dumpbin") {
     |          ~~~~~~~~~~~~~~~~~~~~~
     | The term 'dumpbin' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Normal build using `cmake --build ./build --config Release --target INSTALL` works perfectly fine. It should be something with the path because `dumpbin` is normally accessed via visual studio developer command prompt.

I've created a repo that can reproduce the error above https://github.com/TeSheng93/scikit_build_core_vcpkg_dumpbin

**Comment by henryiii** [comment]
Do you need to activate MSVC, with something like https://github.com/ilammy/msvc-dev-cmd? We don't modify the PATH or do much of anything special with cmake's discovery of MSVC.
