### ISSUE TITLE
Bug: CMake version parsing is too optimistic

### ISSUE THREAD

**Issue by imatlopez** [scikit-build/scikit-build-core#941]
CMake versioning follows the Major.Minor.Patch scheme, but before a new Minor is released it goes through a release candidate phase.  That version will have a postfix. In a debian distribution the version might look like 3.31.0~rc1 (it may also use 3.31.0-rc1).

Scikit minimum cmake version detection is misidentifying the postfix and causing minimum version checks to fail.

```
Running command Preparing metadata (pyproject.toml)
  2024-10-22 09:26:52,163 - scikit_build_core - INFO - RUN: /opt/bb/bin/cmake -E capabilities
  2024-10-22 09:26:52,166 - scikit_build_core - INFO - CMake version: 3.31.0rc2
  scikit_build_core.errors.CMakeNotFoundError: Could not find CMake with version >=3.15
```

3.31.0~rc2 does satisfy >=3.15

Versions tested against: 0.9.4

**Comment by imatlopez** [comment]
https://github.com/scikit-build/scikit-build-core/issues/833 need to try 0.9.9

**Comment by henryiii** [comment]
I don't think we support `~`, just `-`. Does it report the `~` in the programatic version? Or not have a separator at all? If so, we might need to adapt.

**Comment by henryiii** [comment]
I think that as long as it doesn't have a `~`, it likely is fine, since we process with `packaging.version.Version`.
