### ISSUE TITLE
Unable to override compile flags to disable warnings as errors

### ISSUE THREAD

**Issue by andreamancuso** [scikit-build/scikit-build-core#950]
Hi,
I'm going a bit nuts with this one. I've got a PR on my own project: https://github.com/xframes-project/xframes/pull/89

Despite my attempts, I keep getting:

```
error C2220: the following warning is treated as an error [C:\Users\manes
\AppData\Local\Temp\tmp8mgsgeud\build\xframes.vcxproj]
```

I am using Windows 11 and VS 2022.

I tried `add_compile_options(/WX-)` but I have a suspicion that this is overridden somewhere. Can you please give me any pointers?

**Comment by henryiii** [comment]
Isn't it `/WX:NO`? https://learn.microsoft.com/en-us/cpp/build/reference/wx-treat-linker-warnings-as-errors?view=msvc-170

**Comment by andreamancuso** [comment]
Ouch. Sorry.
